
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-09T10:25:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "284af55d115bbf51114f69496e2f7146bafbbcb9",
 "version": "v0.6.7-beta.4"
}
'''  # END VERSION_JSON


def get_versions():
    """Get versions short version."""
    return json.loads(version_json)
