
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-07T20:25:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e298e8fb7f047fc59ebdd9eee02a04338cd18cf7",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
