
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T10:27:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb2ea74dbce0e2395a9c8cae686b804a7302e9d3",
 "version": "1.17.1.post0.dev351"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
