# Generated File
import typing

import retro_data_structures.properties.echoes.objects.AIHint as _AIHint_Echoes
import retro_data_structures.properties.corruption.objects.AIHint as _AIHint_Corruption
import retro_data_structures.properties.dkc_returns.objects.AIHint as _AIHint_DKCReturns
import retro_data_structures.properties.prime.objects.AIJumpPoint as _AIJumpPoint_Prime
import retro_data_structures.properties.echoes.objects.AIJumpPoint as _AIJumpPoint_Echoes
import retro_data_structures.properties.prime.objects.AIKeyframe as _AIKeyframe_Prime
import retro_data_structures.properties.echoes.objects.AIKeyframe as _AIKeyframe_Echoes
import retro_data_structures.properties.corruption.objects.AIKeyframe as _AIKeyframe_Corruption
import retro_data_structures.properties.dkc_returns.objects.AIKeyframe as _AIKeyframe_DKCReturns
import retro_data_structures.properties.echoes.objects.AIWaypoint as _AIWaypoint_Echoes
import retro_data_structures.properties.corruption.objects.AIWaypoint as _AIWaypoint_Corruption
import retro_data_structures.properties.dkc_returns.objects.AIWaypoint as _AIWaypoint_DKCReturns
import retro_data_structures.properties.corruption.objects.AVIS as _AVIS_Corruption
import retro_data_structures.properties.dkc_returns.objects.AVIS as _AVIS_DKCReturns
import retro_data_structures.properties.prime.objects.Actor as _Actor_Prime
import retro_data_structures.properties.echoes.objects.Actor as _Actor_Echoes
import retro_data_structures.properties.corruption.objects.Actor as _Actor_Corruption
import retro_data_structures.properties.dkc_returns.objects.Actor as _Actor_DKCReturns
import retro_data_structures.properties.prime.objects.ActorKeyframe as _ActorKeyframe_Prime
import retro_data_structures.properties.echoes.objects.ActorKeyframe as _ActorKeyframe_Echoes
import retro_data_structures.properties.corruption.objects.ActorKeyframe as _ActorKeyframe_Corruption
import retro_data_structures.properties.dkc_returns.objects.ActorKeyframe as _ActorKeyframe_DKCReturns
import retro_data_structures.properties.prime.objects.ActorRotate as _ActorRotate_Prime
import retro_data_structures.properties.echoes.objects.ActorRotate as _ActorRotate_Echoes
import retro_data_structures.properties.corruption.objects.ActorTransform as _ActorTransform_Corruption
import retro_data_structures.properties.dkc_returns.objects.ActorTransform as _ActorTransform_DKCReturns
import retro_data_structures.properties.prime.objects.AmbientAI as _AmbientAI_Prime
import retro_data_structures.properties.echoes.objects.AmbientAI as _AmbientAI_Echoes
import retro_data_structures.properties.corruption.objects.AmbientAI as _AmbientAI_Corruption
import retro_data_structures.properties.prime.objects.AreaAttributes as _AreaAttributes_Prime
import retro_data_structures.properties.echoes.objects.AreaAttributes as _AreaAttributes_Echoes
import retro_data_structures.properties.corruption.objects.AreaAttributes as _AreaAttributes_Corruption
import retro_data_structures.properties.dkc_returns.objects.AreaAttributes as _AreaAttributes_DKCReturns
import retro_data_structures.properties.echoes.objects.AreaDamage as _AreaDamage_Echoes
import retro_data_structures.properties.corruption.objects.AreaDamage as _AreaDamage_Corruption
import retro_data_structures.properties.dkc_returns.objects.AreaDamage as _AreaDamage_DKCReturns
import retro_data_structures.properties.corruption.objects.AreaStreamedAudioState as _AreaStreamedAudioState_Corruption
import retro_data_structures.properties.dkc_returns.objects.AreaStreamedAudioState as _AreaStreamedAudioState_DKCReturns
import retro_data_structures.properties.prime.objects.AtomicAlpha as _AtomicAlpha_Prime
import retro_data_structures.properties.echoes.objects.AtomicAlpha as _AtomicAlpha_Echoes
import retro_data_structures.properties.corruption.objects.AtomicAlpha as _AtomicAlpha_Corruption
import retro_data_structures.properties.prime.objects.AtomicBeta as _AtomicBeta_Prime
import retro_data_structures.properties.echoes.objects.AtomicBeta as _AtomicBeta_Echoes
import retro_data_structures.properties.corruption.objects.AudioOccluder as _AudioOccluder_Corruption
import retro_data_structures.properties.dkc_returns.objects.AudioOccluder as _AudioOccluder_DKCReturns
import retro_data_structures.properties.prime.objects.BallTrigger as _BallTrigger_Prime
import retro_data_structures.properties.echoes.objects.BallTrigger as _BallTrigger_Echoes
import retro_data_structures.properties.corruption.objects.BallTrigger as _BallTrigger_Corruption
import retro_data_structures.properties.corruption.objects.Cable as _Cable_Corruption
import retro_data_structures.properties.dkc_returns.objects.Cable as _Cable_DKCReturns
import retro_data_structures.properties.prime.objects.Camera as _Camera_Prime
import retro_data_structures.properties.echoes.objects.Camera as _Camera_Echoes
import retro_data_structures.properties.prime.objects.CameraBlurKeyframe as _CameraBlurKeyframe_Prime
import retro_data_structures.properties.echoes.objects.CameraBlurKeyframe as _CameraBlurKeyframe_Echoes
import retro_data_structures.properties.corruption.objects.CameraBlurKeyframe as _CameraBlurKeyframe_Corruption
import retro_data_structures.properties.dkc_returns.objects.CameraBlurKeyframe as _CameraBlurKeyframe_DKCReturns
import retro_data_structures.properties.prime.objects.CameraFilterKeyframe as _CameraFilterKeyframe_Prime
import retro_data_structures.properties.echoes.objects.CameraFilterKeyframe as _CameraFilterKeyframe_Echoes
import retro_data_structures.properties.corruption.objects.CameraFilterKeyframe as _CameraFilterKeyframe_Corruption
import retro_data_structures.properties.dkc_returns.objects.CameraFilterKeyframe as _CameraFilterKeyframe_DKCReturns
import retro_data_structures.properties.prime.objects.CameraHint as _CameraHint_Prime
import retro_data_structures.properties.echoes.objects.CameraHint as _CameraHint_Echoes
import retro_data_structures.properties.corruption.objects.CameraHint as _CameraHint_Corruption
import retro_data_structures.properties.dkc_returns.objects.CameraHint as _CameraHint_DKCReturns
import retro_data_structures.properties.echoes.objects.CameraPitch as _CameraPitch_Echoes
import retro_data_structures.properties.corruption.objects.CameraPitch as _CameraPitch_Corruption
import retro_data_structures.properties.prime.objects.CameraShaker as _CameraShaker_Prime
import retro_data_structures.properties.echoes.objects.CameraShaker as _CameraShaker_Echoes
import retro_data_structures.properties.corruption.objects.CameraShaker as _CameraShaker_Corruption
import retro_data_structures.properties.dkc_returns.objects.CameraShaker as _CameraShaker_DKCReturns
import retro_data_structures.properties.prime.objects.CameraWaypoint as _CameraWaypoint_Prime
import retro_data_structures.properties.echoes.objects.CameraWaypoint as _CameraWaypoint_Echoes
import retro_data_structures.properties.echoes.objects.CannonBall as _CannonBall_Echoes
import retro_data_structures.properties.corruption.objects.CannonBall as _CannonBall_Corruption
import retro_data_structures.properties.prime.objects.ChozoGhost as _ChozoGhost_Prime
import retro_data_structures.properties.echoes.objects.ChozoGhost as _ChozoGhost_Echoes
import retro_data_structures.properties.corruption.objects.CinematicCamera as _CinematicCamera_Corruption
import retro_data_structures.properties.dkc_returns.objects.CinematicCamera as _CinematicCamera_DKCReturns
import retro_data_structures.properties.prime.objects.ColorModulate as _ColorModulate_Prime
import retro_data_structures.properties.echoes.objects.ColorModulate as _ColorModulate_Echoes
import retro_data_structures.properties.corruption.objects.ColorModulate as _ColorModulate_Corruption
import retro_data_structures.properties.dkc_returns.objects.ColorModulate as _ColorModulate_DKCReturns
import retro_data_structures.properties.echoes.objects.ConditionalRelay as _ConditionalRelay_Echoes
import retro_data_structures.properties.corruption.objects.ConditionalRelay as _ConditionalRelay_Corruption
import retro_data_structures.properties.dkc_returns.objects.ConditionalRelay as _ConditionalRelay_DKCReturns
import retro_data_structures.properties.echoes.objects.ControlHint as _ControlHint_Echoes
import retro_data_structures.properties.corruption.objects.ControlHint as _ControlHint_Corruption
import retro_data_structures.properties.prime.objects.ControllerAction as _ControllerAction_Prime
import retro_data_structures.properties.echoes.objects.ControllerAction as _ControllerAction_Echoes
import retro_data_structures.properties.corruption.objects.ControllerAction as _ControllerAction_Corruption
import retro_data_structures.properties.dkc_returns.objects.ControllerAction as _ControllerAction_DKCReturns
import retro_data_structures.properties.prime.objects.Counter as _Counter_Prime
import retro_data_structures.properties.echoes.objects.Counter as _Counter_Echoes
import retro_data_structures.properties.corruption.objects.Counter as _Counter_Corruption
import retro_data_structures.properties.dkc_returns.objects.Counter as _Counter_DKCReturns
import retro_data_structures.properties.prime.objects.CoverPoint as _CoverPoint_Prime
import retro_data_structures.properties.echoes.objects.CoverPoint as _CoverPoint_Echoes
import retro_data_structures.properties.corruption.objects.CoverPoint as _CoverPoint_Corruption
import retro_data_structures.properties.echoes.objects.DamageActor as _DamageActor_Echoes
import retro_data_structures.properties.corruption.objects.DamageActor as _DamageActor_Corruption
import retro_data_structures.properties.prime.objects.DamageableTrigger as _DamageableTrigger_Prime
import retro_data_structures.properties.echoes.objects.DamageableTrigger as _DamageableTrigger_Echoes
import retro_data_structures.properties.corruption.objects.DamageableTrigger as _DamageableTrigger_Corruption
import retro_data_structures.properties.dkc_returns.objects.DamageableTrigger as _DamageableTrigger_DKCReturns
import retro_data_structures.properties.echoes.objects.DamageableTriggerOrientated as _DamageableTriggerOrientated_Echoes
import retro_data_structures.properties.corruption.objects.DamageableTriggerOrientated as _DamageableTriggerOrientated_Corruption
import retro_data_structures.properties.dkc_returns.objects.DamageableTriggerOrientated as _DamageableTriggerOrientated_DKCReturns
import retro_data_structures.properties.echoes.objects.DarkSamus as _DarkSamus_Echoes
import retro_data_structures.properties.corruption.objects.DarkSamus as _DarkSamus_Corruption
import retro_data_structures.properties.prime.objects.Debris as _Debris_Prime
import retro_data_structures.properties.echoes.objects.Debris as _Debris_Echoes
import retro_data_structures.properties.corruption.objects.Debris as _Debris_Corruption
import retro_data_structures.properties.dkc_returns.objects.Debris as _Debris_DKCReturns
import retro_data_structures.properties.prime.objects.DebrisExtended as _DebrisExtended_Prime
import retro_data_structures.properties.echoes.objects.DebrisExtended as _DebrisExtended_Echoes
import retro_data_structures.properties.prime.objects.DistanceFog as _DistanceFog_Prime
import retro_data_structures.properties.echoes.objects.DistanceFog as _DistanceFog_Echoes
import retro_data_structures.properties.corruption.objects.DistanceFog as _DistanceFog_Corruption
import retro_data_structures.properties.dkc_returns.objects.DistanceFog as _DistanceFog_DKCReturns
import retro_data_structures.properties.prime.objects.Dock as _Dock_Prime
import retro_data_structures.properties.echoes.objects.Dock as _Dock_Echoes
import retro_data_structures.properties.corruption.objects.Dock as _Dock_Corruption
import retro_data_structures.properties.prime.objects.Door as _Door_Prime
import retro_data_structures.properties.echoes.objects.Door as _Door_Echoes
import retro_data_structures.properties.corruption.objects.Door as _Door_Corruption
import retro_data_structures.properties.echoes.objects.DynamicLight as _DynamicLight_Echoes
import retro_data_structures.properties.corruption.objects.DynamicLight as _DynamicLight_Corruption
import retro_data_structures.properties.dkc_returns.objects.DynamicLight as _DynamicLight_DKCReturns
import retro_data_structures.properties.prime.objects.Effect as _Effect_Prime
import retro_data_structures.properties.echoes.objects.Effect as _Effect_Echoes
import retro_data_structures.properties.corruption.objects.Effect as _Effect_Corruption
import retro_data_structures.properties.dkc_returns.objects.Effect as _Effect_DKCReturns
import retro_data_structures.properties.prime.objects.ElectroMagneticPulse as _ElectroMagneticPulse_Prime
import retro_data_structures.properties.corruption.objects.ElectroMagneticPulse as _ElectroMagneticPulse_Corruption
import retro_data_structures.properties.prime.objects.ElitePirate as _ElitePirate_Prime
import retro_data_structures.properties.echoes.objects.ElitePirate as _ElitePirate_Echoes
import retro_data_structures.properties.prime.objects.EnvFxDensityController as _EnvFxDensityController_Prime
import retro_data_structures.properties.echoes.objects.EnvFxDensityController as _EnvFxDensityController_Echoes
import retro_data_structures.properties.corruption.objects.EnvFxDensityController as _EnvFxDensityController_Corruption
import retro_data_structures.properties.dkc_returns.objects.EnvFxDensityController as _EnvFxDensityController_DKCReturns
import retro_data_structures.properties.corruption.objects.FalsePerspective as _FalsePerspective_Corruption
import retro_data_structures.properties.dkc_returns.objects.FalsePerspective as _FalsePerspective_DKCReturns
import retro_data_structures.properties.prime.objects.FishCloud as _FishCloud_Prime
import retro_data_structures.properties.echoes.objects.FishCloud as _FishCloud_Echoes
import retro_data_structures.properties.corruption.objects.FishCloud as _FishCloud_Corruption
import retro_data_structures.properties.prime.objects.FishCloudModifier as _FishCloudModifier_Prime
import retro_data_structures.properties.echoes.objects.FishCloudModifier as _FishCloudModifier_Echoes
import retro_data_structures.properties.corruption.objects.FishCloudModifier as _FishCloudModifier_Corruption
import retro_data_structures.properties.echoes.objects.FlyerSwarm as _FlyerSwarm_Echoes
import retro_data_structures.properties.corruption.objects.FlyerSwarm as _FlyerSwarm_Corruption
import retro_data_structures.properties.prime.objects.FlyingPirate as _FlyingPirate_Prime
import retro_data_structures.properties.echoes.objects.FlyingPirate as _FlyingPirate_Echoes
import retro_data_structures.properties.corruption.objects.FlyingPirate as _FlyingPirate_Corruption
import retro_data_structures.properties.echoes.objects.FogOverlay as _FogOverlay_Echoes
import retro_data_structures.properties.corruption.objects.FogOverlay as _FogOverlay_Corruption
import retro_data_structures.properties.dkc_returns.objects.FogOverlay as _FogOverlay_DKCReturns
import retro_data_structures.properties.prime.objects.FogVolume as _FogVolume_Prime
import retro_data_structures.properties.echoes.objects.FogVolume as _FogVolume_Echoes
import retro_data_structures.properties.corruption.objects.FogVolume as _FogVolume_Corruption
import retro_data_structures.properties.dkc_returns.objects.FogVolume as _FogVolume_DKCReturns
import retro_data_structures.properties.corruption.objects.GeneratedObjectDeleter as _GeneratedObjectDeleter_Corruption
import retro_data_structures.properties.dkc_returns.objects.GeneratedObjectDeleter as _GeneratedObjectDeleter_DKCReturns
import retro_data_structures.properties.prime.objects.Generator as _Generator_Prime
import retro_data_structures.properties.echoes.objects.Generator as _Generator_Echoes
import retro_data_structures.properties.corruption.objects.Generator as _Generator_Corruption
import retro_data_structures.properties.dkc_returns.objects.Generator as _Generator_DKCReturns
import retro_data_structures.properties.prime.objects.GrapplePoint as _GrapplePoint_Prime
import retro_data_structures.properties.echoes.objects.GrapplePoint as _GrapplePoint_Echoes
import retro_data_structures.properties.corruption.objects.GrapplePoint as _GrapplePoint_Corruption
import retro_data_structures.properties.echoes.objects.GuiMenu as _GuiMenu_Echoes
import retro_data_structures.properties.corruption.objects.GuiMenu as _GuiMenu_Corruption
import retro_data_structures.properties.dkc_returns.objects.GuiMenu as _GuiMenu_DKCReturns
import retro_data_structures.properties.echoes.objects.GuiScreen as _GuiScreen_Echoes
import retro_data_structures.properties.corruption.objects.GuiScreen as _GuiScreen_Corruption
import retro_data_structures.properties.echoes.objects.GuiSlider as _GuiSlider_Echoes
import retro_data_structures.properties.corruption.objects.GuiSlider as _GuiSlider_Corruption
import retro_data_structures.properties.dkc_returns.objects.GuiSlider as _GuiSlider_DKCReturns
import retro_data_structures.properties.echoes.objects.GuiWidget as _GuiWidget_Echoes
import retro_data_structures.properties.corruption.objects.GuiWidget as _GuiWidget_Corruption
import retro_data_structures.properties.dkc_returns.objects.GuiWidget as _GuiWidget_DKCReturns
import retro_data_structures.properties.echoes.objects.GunTurretBase as _GunTurretBase_Echoes
import retro_data_structures.properties.corruption.objects.GunTurretBase as _GunTurretBase_Corruption
import retro_data_structures.properties.echoes.objects.GunTurretTop as _GunTurretTop_Echoes
import retro_data_structures.properties.corruption.objects.GunTurretTop as _GunTurretTop_Corruption
import retro_data_structures.properties.echoes.objects.HUDHint as _HUDHint_Echoes
import retro_data_structures.properties.corruption.objects.HUDHint as _HUDHint_Corruption
import retro_data_structures.properties.prime.objects.HUDMemo as _HUDMemo_Prime
import retro_data_structures.properties.echoes.objects.HUDMemo as _HUDMemo_Echoes
import retro_data_structures.properties.corruption.objects.HUDMemo as _HUDMemo_Corruption
import retro_data_structures.properties.corruption.objects.LODController as _LODController_Corruption
import retro_data_structures.properties.dkc_returns.objects.LODController as _LODController_DKCReturns
import retro_data_structures.properties.corruption.objects.LightVolume as _LightVolume_Corruption
import retro_data_structures.properties.dkc_returns.objects.LightVolume as _LightVolume_DKCReturns
import retro_data_structures.properties.prime.objects.MemoryRelay as _MemoryRelay_Prime
import retro_data_structures.properties.echoes.objects.MemoryRelay as _MemoryRelay_Echoes
import retro_data_structures.properties.corruption.objects.MemoryRelay as _MemoryRelay_Corruption
import retro_data_structures.properties.dkc_returns.objects.MemoryRelay as _MemoryRelay_DKCReturns
import retro_data_structures.properties.echoes.objects.Metaree as _Metaree_Echoes
import retro_data_structures.properties.corruption.objects.Metaree as _Metaree_Corruption
import retro_data_structures.properties.prime.objects.MetroidAlpha as _MetroidAlpha_Prime
import retro_data_structures.properties.echoes.objects.MetroidAlpha as _MetroidAlpha_Echoes
import retro_data_structures.properties.prime.objects.Midi as _Midi_Prime
import retro_data_structures.properties.echoes.objects.Midi as _Midi_Echoes
import retro_data_structures.properties.echoes.objects.MinorIng as _MinorIng_Echoes
import retro_data_structures.properties.corruption.objects.MinorIng as _MinorIng_Corruption
import retro_data_structures.properties.corruption.objects.MultiModelActor as _MultiModelActor_Corruption
import retro_data_structures.properties.dkc_returns.objects.MultiModelActor as _MultiModelActor_DKCReturns
import retro_data_structures.properties.echoes.objects.MysteryFlyer as _MysteryFlyer_Echoes
import retro_data_structures.properties.corruption.objects.MysteryFlyer as _MysteryFlyer_Corruption
import retro_data_structures.properties.corruption.objects.OptionalAreaAsset as _OptionalAreaAsset_Corruption
import retro_data_structures.properties.dkc_returns.objects.OptionalAreaAsset as _OptionalAreaAsset_DKCReturns
import retro_data_structures.properties.prime.objects.Parasite as _Parasite_Prime
import retro_data_structures.properties.echoes.objects.Parasite as _Parasite_Echoes
import retro_data_structures.properties.corruption.objects.Parasite as _Parasite_Corruption
import retro_data_structures.properties.prime.objects.PathCamera as _PathCamera_Prime
import retro_data_structures.properties.echoes.objects.PathCamera as _PathCamera_Echoes
import retro_data_structures.properties.corruption.objects.PathControl as _PathControl_Corruption
import retro_data_structures.properties.dkc_returns.objects.PathControl as _PathControl_DKCReturns
import retro_data_structures.properties.echoes.objects.PathMeshCtrl as _PathMeshCtrl_Echoes
import retro_data_structures.properties.corruption.objects.PathMeshCtrl as _PathMeshCtrl_Corruption
import retro_data_structures.properties.prime.objects.Pickup as _Pickup_Prime
import retro_data_structures.properties.echoes.objects.Pickup as _Pickup_Echoes
import retro_data_structures.properties.corruption.objects.Pickup as _Pickup_Corruption
import retro_data_structures.properties.dkc_returns.objects.Pickup as _Pickup_DKCReturns
import retro_data_structures.properties.prime.objects.PickupGenerator as _PickupGenerator_Prime
import retro_data_structures.properties.echoes.objects.PickupGenerator as _PickupGenerator_Echoes
import retro_data_structures.properties.echoes.objects.PillBug as _PillBug_Echoes
import retro_data_structures.properties.corruption.objects.PillBug as _PillBug_Corruption
import retro_data_structures.properties.echoes.objects.PlantScarabSwarm as _PlantScarabSwarm_Echoes
import retro_data_structures.properties.corruption.objects.PlantScarabSwarm as _PlantScarabSwarm_Corruption
import retro_data_structures.properties.prime.objects.Platform as _Platform_Prime
import retro_data_structures.properties.echoes.objects.Platform as _Platform_Echoes
import retro_data_structures.properties.corruption.objects.Platform as _Platform_Corruption
import retro_data_structures.properties.dkc_returns.objects.Platform as _Platform_DKCReturns
import retro_data_structures.properties.prime.objects.PlayerActor as _PlayerActor_Prime
import retro_data_structures.properties.echoes.objects.PlayerActor as _PlayerActor_Echoes
import retro_data_structures.properties.corruption.objects.PlayerActor as _PlayerActor_Corruption
import retro_data_structures.properties.dkc_returns.objects.PlayerActor as _PlayerActor_DKCReturns
import retro_data_structures.properties.prime.objects.PlayerHint as _PlayerHint_Prime
import retro_data_structures.properties.echoes.objects.PlayerHint as _PlayerHint_Echoes
import retro_data_structures.properties.corruption.objects.PlayerHint as _PlayerHint_Corruption
import retro_data_structures.properties.prime.objects.PlayerStateChange as _PlayerStateChange_Prime
import retro_data_structures.properties.echoes.objects.PlayerStateChange as _PlayerStateChange_Echoes
import retro_data_structures.properties.prime.objects.PointOfInterest as _PointOfInterest_Prime
import retro_data_structures.properties.echoes.objects.PointOfInterest as _PointOfInterest_Echoes
import retro_data_structures.properties.corruption.objects.PointOfInterest as _PointOfInterest_Corruption
import retro_data_structures.properties.corruption.objects.PositionRelay as _PositionRelay_Corruption
import retro_data_structures.properties.dkc_returns.objects.PositionRelay as _PositionRelay_DKCReturns
import retro_data_structures.properties.prime.objects.PuddleSpore as _PuddleSpore_Prime
import retro_data_structures.properties.echoes.objects.PuddleSpore as _PuddleSpore_Echoes
import retro_data_structures.properties.prime.objects.Puffer as _Puffer_Prime
import retro_data_structures.properties.echoes.objects.Puffer as _Puffer_Echoes
import retro_data_structures.properties.corruption.objects.Puffer as _Puffer_Corruption
import retro_data_structures.properties.prime.objects.RadialDamage as _RadialDamage_Prime
import retro_data_structures.properties.echoes.objects.RadialDamage as _RadialDamage_Echoes
import retro_data_structures.properties.corruption.objects.RadialDamage as _RadialDamage_Corruption
import retro_data_structures.properties.dkc_returns.objects.RadialDamage as _RadialDamage_DKCReturns
import retro_data_structures.properties.prime.objects.RandomRelay as _RandomRelay_Prime
import retro_data_structures.properties.echoes.objects.RandomRelay as _RandomRelay_Echoes
import retro_data_structures.properties.corruption.objects.RandomRelay as _RandomRelay_Corruption
import retro_data_structures.properties.prime.objects.Relay as _Relay_Prime
import retro_data_structures.properties.echoes.objects.Relay as _Relay_Echoes
import retro_data_structures.properties.corruption.objects.Relay as _Relay_Corruption
import retro_data_structures.properties.dkc_returns.objects.Relay as _Relay_DKCReturns
import retro_data_structures.properties.prime.objects.Repulsor as _Repulsor_Prime
import retro_data_structures.properties.echoes.objects.Repulsor as _Repulsor_Echoes
import retro_data_structures.properties.corruption.objects.Repulsor as _Repulsor_Corruption
import retro_data_structures.properties.prime.objects.Ripper as _Ripper_Prime
import retro_data_structures.properties.echoes.objects.Ripper as _Ripper_Echoes
import retro_data_structures.properties.prime.objects.Ripple as _Ripple_Prime
import retro_data_structures.properties.echoes.objects.Ripple as _Ripple_Echoes
import retro_data_structures.properties.corruption.objects.Ripple as _Ripple_Corruption
import retro_data_structures.properties.prime.objects.RoomAcoustics as _RoomAcoustics_Prime
import retro_data_structures.properties.echoes.objects.RoomAcoustics as _RoomAcoustics_Echoes
import retro_data_structures.properties.corruption.objects.RoomAcoustics as _RoomAcoustics_Corruption
import retro_data_structures.properties.prime.objects.RumbleEffect as _RumbleEffect_Prime
import retro_data_structures.properties.echoes.objects.RumbleEffect as _RumbleEffect_Echoes
import retro_data_structures.properties.corruption.objects.RumbleEffect as _RumbleEffect_Corruption
import retro_data_structures.properties.dkc_returns.objects.RumbleEffect as _RumbleEffect_DKCReturns
import retro_data_structures.properties.echoes.objects.ScriptLayerController as _ScriptLayerController_Echoes
import retro_data_structures.properties.corruption.objects.ScriptLayerController as _ScriptLayerController_Corruption
import retro_data_structures.properties.dkc_returns.objects.ScriptLayerController as _ScriptLayerController_DKCReturns
import retro_data_structures.properties.echoes.objects.SequenceTimer as _SequenceTimer_Echoes
import retro_data_structures.properties.corruption.objects.SequenceTimer as _SequenceTimer_Corruption
import retro_data_structures.properties.dkc_returns.objects.SequenceTimer as _SequenceTimer_DKCReturns
import retro_data_structures.properties.prime.objects.ShadowProjector as _ShadowProjector_Prime
import retro_data_structures.properties.echoes.objects.ShadowProjector as _ShadowProjector_Echoes
import retro_data_structures.properties.corruption.objects.ShadowProjector as _ShadowProjector_Corruption
import retro_data_structures.properties.dkc_returns.objects.ShadowProjector as _ShadowProjector_DKCReturns
import retro_data_structures.properties.echoes.objects.SkyRipple as _SkyRipple_Echoes
import retro_data_structures.properties.corruption.objects.SkyRipple as _SkyRipple_Corruption
import retro_data_structures.properties.corruption.objects.SkyboxModInca as _SkyboxModInca_Corruption
import retro_data_structures.properties.dkc_returns.objects.SkyboxModInca as _SkyboxModInca_DKCReturns
import retro_data_structures.properties.prime.objects.SnakeWeedSwarm as _SnakeWeedSwarm_Prime
import retro_data_structures.properties.echoes.objects.SnakeWeedSwarm as _SnakeWeedSwarm_Echoes
import retro_data_structures.properties.prime.objects.Sound as _Sound_Prime
import retro_data_structures.properties.echoes.objects.Sound as _Sound_Echoes
import retro_data_structures.properties.corruption.objects.Sound as _Sound_Corruption
import retro_data_structures.properties.dkc_returns.objects.Sound as _Sound_DKCReturns
import retro_data_structures.properties.echoes.objects.SoundModifier as _SoundModifier_Echoes
import retro_data_structures.properties.corruption.objects.SoundModifier as _SoundModifier_Corruption
import retro_data_structures.properties.dkc_returns.objects.SoundModifier as _SoundModifier_DKCReturns
import retro_data_structures.properties.prime.objects.SpacePirate as _SpacePirate_Prime
import retro_data_structures.properties.echoes.objects.SpacePirate as _SpacePirate_Echoes
import retro_data_structures.properties.corruption.objects.SpacePirate as _SpacePirate_Corruption
import retro_data_structures.properties.prime.objects.SpankWeed as _SpankWeed_Prime
import retro_data_structures.properties.echoes.objects.SpankWeed as _SpankWeed_Echoes
import retro_data_structures.properties.prime.objects.SpawnPoint as _SpawnPoint_Prime
import retro_data_structures.properties.echoes.objects.SpawnPoint as _SpawnPoint_Echoes
import retro_data_structures.properties.corruption.objects.SpawnPoint as _SpawnPoint_Corruption
import retro_data_structures.properties.dkc_returns.objects.SpawnPoint as _SpawnPoint_DKCReturns
import retro_data_structures.properties.prime.objects.SpecialFunction as _SpecialFunction_Prime
import retro_data_structures.properties.echoes.objects.SpecialFunction as _SpecialFunction_Echoes
import retro_data_structures.properties.corruption.objects.SpecialFunction as _SpecialFunction_Corruption
import retro_data_structures.properties.dkc_returns.objects.SpecialFunction as _SpecialFunction_DKCReturns
import retro_data_structures.properties.prime.objects.SpiderBallAttractionSurface as _SpiderBallAttractionSurface_Prime
import retro_data_structures.properties.echoes.objects.SpiderBallAttractionSurface as _SpiderBallAttractionSurface_Echoes
import retro_data_structures.properties.corruption.objects.SpiderBallAttractionSurface as _SpiderBallAttractionSurface_Corruption
import retro_data_structures.properties.prime.objects.SpiderBallWaypoint as _SpiderBallWaypoint_Prime
import retro_data_structures.properties.echoes.objects.SpiderBallWaypoint as _SpiderBallWaypoint_Echoes
import retro_data_structures.properties.corruption.objects.SpiderBallWaypoint as _SpiderBallWaypoint_Corruption
import retro_data_structures.properties.prime.objects.SpindleCamera as _SpindleCamera_Prime
import retro_data_structures.properties.echoes.objects.SpindleCamera as _SpindleCamera_Echoes
import retro_data_structures.properties.echoes.objects.Spinner as _Spinner_Echoes
import retro_data_structures.properties.corruption.objects.Spinner as _Spinner_Corruption
import retro_data_structures.properties.dkc_returns.objects.Spinner as _Spinner_DKCReturns
import retro_data_structures.properties.prime.objects.Steam as _Steam_Prime
import retro_data_structures.properties.echoes.objects.Steam as _Steam_Echoes
import retro_data_structures.properties.corruption.objects.Steam as _Steam_Corruption
import retro_data_structures.properties.prime.objects.StreamedAudio as _StreamedAudio_Prime
import retro_data_structures.properties.echoes.objects.StreamedAudio as _StreamedAudio_Echoes
import retro_data_structures.properties.corruption.objects.StreamedAudio as _StreamedAudio_Corruption
import retro_data_structures.properties.dkc_returns.objects.StreamedAudio as _StreamedAudio_DKCReturns
import retro_data_structures.properties.echoes.objects.StreamedMovie as _StreamedMovie_Echoes
import retro_data_structures.properties.corruption.objects.StreamedMovie as _StreamedMovie_Corruption
import retro_data_structures.properties.dkc_returns.objects.StreamedMovie as _StreamedMovie_DKCReturns
import retro_data_structures.properties.corruption.objects.Subtitles as _Subtitles_Corruption
import retro_data_structures.properties.dkc_returns.objects.Subtitles as _Subtitles_DKCReturns
import retro_data_structures.properties.corruption.objects.SurfaceControl as _SurfaceControl_Corruption
import retro_data_structures.properties.dkc_returns.objects.SurfaceControl as _SurfaceControl_DKCReturns
import retro_data_structures.properties.prime.objects.Switch as _Switch_Prime
import retro_data_structures.properties.echoes.objects.Switch as _Switch_Echoes
import retro_data_structures.properties.corruption.objects.Switch as _Switch_Corruption
import retro_data_structures.properties.dkc_returns.objects.Switch as _Switch_DKCReturns
import retro_data_structures.properties.prime.objects.TargetingPoint as _TargetingPoint_Prime
import retro_data_structures.properties.echoes.objects.TargetingPoint as _TargetingPoint_Echoes
import retro_data_structures.properties.corruption.objects.TargetingPoint as _TargetingPoint_Corruption
import retro_data_structures.properties.echoes.objects.TeamAI as _TeamAI_Echoes
import retro_data_structures.properties.corruption.objects.TeamAI as _TeamAI_Corruption
import retro_data_structures.properties.echoes.objects.TextPane as _TextPane_Echoes
import retro_data_structures.properties.corruption.objects.TextPane as _TextPane_Corruption
import retro_data_structures.properties.dkc_returns.objects.TextPane as _TextPane_DKCReturns
import retro_data_structures.properties.echoes.objects.TimeKeyframe as _TimeKeyframe_Echoes
import retro_data_structures.properties.corruption.objects.TimeKeyframe as _TimeKeyframe_Corruption
import retro_data_structures.properties.dkc_returns.objects.TimeKeyframe as _TimeKeyframe_DKCReturns
import retro_data_structures.properties.prime.objects.Timer as _Timer_Prime
import retro_data_structures.properties.echoes.objects.Timer as _Timer_Echoes
import retro_data_structures.properties.corruption.objects.Timer as _Timer_Corruption
import retro_data_structures.properties.dkc_returns.objects.Timer as _Timer_DKCReturns
import retro_data_structures.properties.prime.objects.Trigger as _Trigger_Prime
import retro_data_structures.properties.echoes.objects.Trigger as _Trigger_Echoes
import retro_data_structures.properties.corruption.objects.Trigger as _Trigger_Corruption
import retro_data_structures.properties.dkc_returns.objects.Trigger as _Trigger_DKCReturns
import retro_data_structures.properties.prime.objects.Tryclops as _Tryclops_Prime
import retro_data_structures.properties.echoes.objects.Tryclops as _Tryclops_Echoes
import retro_data_structures.properties.prime.objects.VisorFlare as _VisorFlare_Prime
import retro_data_structures.properties.echoes.objects.VisorFlare as _VisorFlare_Echoes
import retro_data_structures.properties.corruption.objects.VisorFlare as _VisorFlare_Corruption
import retro_data_structures.properties.prime.objects.VisorGoo as _VisorGoo_Prime
import retro_data_structures.properties.echoes.objects.VisorGoo as _VisorGoo_Echoes
import retro_data_structures.properties.corruption.objects.VisorGoo as _VisorGoo_Corruption
import retro_data_structures.properties.prime.objects.WallCrawlerSwarm as _WallCrawlerSwarm_Prime
import retro_data_structures.properties.corruption.objects.WallCrawlerSwarm as _WallCrawlerSwarm_Corruption
import retro_data_structures.properties.prime.objects.Water as _Water_Prime
import retro_data_structures.properties.echoes.objects.Water as _Water_Echoes
import retro_data_structures.properties.corruption.objects.Water as _Water_Corruption
import retro_data_structures.properties.prime.objects.Waypoint as _Waypoint_Prime
import retro_data_structures.properties.echoes.objects.Waypoint as _Waypoint_Echoes
import retro_data_structures.properties.corruption.objects.Waypoint as _Waypoint_Corruption
import retro_data_structures.properties.dkc_returns.objects.Waypoint as _Waypoint_DKCReturns
import retro_data_structures.properties.corruption.objects.WorldAttributes as _WorldAttributes_Corruption
import retro_data_structures.properties.dkc_returns.objects.WorldAttributes as _WorldAttributes_DKCReturns
import retro_data_structures.properties.prime.objects.WorldLightFader as _WorldLightFader_Prime
import retro_data_structures.properties.echoes.objects.WorldLightFader as _WorldLightFader_Echoes
import retro_data_structures.properties.corruption.objects.WorldLightFader as _WorldLightFader_Corruption
import retro_data_structures.properties.dkc_returns.objects.WorldLightFader as _WorldLightFader_DKCReturns
import retro_data_structures.properties.prime.objects.WorldTeleporter as _WorldTeleporter_Prime
import retro_data_structures.properties.echoes.objects.WorldTeleporter as _WorldTeleporter_Echoes
import retro_data_structures.properties.corruption.objects.WorldTeleporter as _WorldTeleporter_Corruption

AIHint = typing.Union[_AIHint_Echoes.AIHint, _AIHint_Corruption.AIHint, _AIHint_DKCReturns.AIHint]
AIJumpPoint = typing.Union[_AIJumpPoint_Prime.AIJumpPoint, _AIJumpPoint_Echoes.AIJumpPoint]
AIKeyframe = typing.Union[_AIKeyframe_Prime.AIKeyframe, _AIKeyframe_Echoes.AIKeyframe, _AIKeyframe_Corruption.AIKeyframe, _AIKeyframe_DKCReturns.AIKeyframe]
AIWaypoint = typing.Union[_AIWaypoint_Echoes.AIWaypoint, _AIWaypoint_Corruption.AIWaypoint, _AIWaypoint_DKCReturns.AIWaypoint]
AVIS = typing.Union[_AVIS_Corruption.AVIS, _AVIS_DKCReturns.AVIS]
Actor = typing.Union[_Actor_Prime.Actor, _Actor_Echoes.Actor, _Actor_Corruption.Actor, _Actor_DKCReturns.Actor]
ActorKeyframe = typing.Union[_ActorKeyframe_Prime.ActorKeyframe, _ActorKeyframe_Echoes.ActorKeyframe, _ActorKeyframe_Corruption.ActorKeyframe, _ActorKeyframe_DKCReturns.ActorKeyframe]
ActorRotate = typing.Union[_ActorRotate_Prime.ActorRotate, _ActorRotate_Echoes.ActorRotate]
ActorTransform = typing.Union[_ActorTransform_Corruption.ActorTransform, _ActorTransform_DKCReturns.ActorTransform]
AmbientAI = typing.Union[_AmbientAI_Prime.AmbientAI, _AmbientAI_Echoes.AmbientAI, _AmbientAI_Corruption.AmbientAI]
AreaAttributes = typing.Union[_AreaAttributes_Prime.AreaAttributes, _AreaAttributes_Echoes.AreaAttributes, _AreaAttributes_Corruption.AreaAttributes, _AreaAttributes_DKCReturns.AreaAttributes]
AreaDamage = typing.Union[_AreaDamage_Echoes.AreaDamage, _AreaDamage_Corruption.AreaDamage, _AreaDamage_DKCReturns.AreaDamage]
AreaStreamedAudioState = typing.Union[_AreaStreamedAudioState_Corruption.AreaStreamedAudioState, _AreaStreamedAudioState_DKCReturns.AreaStreamedAudioState]
AtomicAlpha = typing.Union[_AtomicAlpha_Prime.AtomicAlpha, _AtomicAlpha_Echoes.AtomicAlpha, _AtomicAlpha_Corruption.AtomicAlpha]
AtomicBeta = typing.Union[_AtomicBeta_Prime.AtomicBeta, _AtomicBeta_Echoes.AtomicBeta]
AudioOccluder = typing.Union[_AudioOccluder_Corruption.AudioOccluder, _AudioOccluder_DKCReturns.AudioOccluder]
BallTrigger = typing.Union[_BallTrigger_Prime.BallTrigger, _BallTrigger_Echoes.BallTrigger, _BallTrigger_Corruption.BallTrigger]
Cable = typing.Union[_Cable_Corruption.Cable, _Cable_DKCReturns.Cable]
Camera = typing.Union[_Camera_Prime.Camera, _Camera_Echoes.Camera]
CameraBlurKeyframe = typing.Union[_CameraBlurKeyframe_Prime.CameraBlurKeyframe, _CameraBlurKeyframe_Echoes.CameraBlurKeyframe, _CameraBlurKeyframe_Corruption.CameraBlurKeyframe, _CameraBlurKeyframe_DKCReturns.CameraBlurKeyframe]
CameraFilterKeyframe = typing.Union[_CameraFilterKeyframe_Prime.CameraFilterKeyframe, _CameraFilterKeyframe_Echoes.CameraFilterKeyframe, _CameraFilterKeyframe_Corruption.CameraFilterKeyframe, _CameraFilterKeyframe_DKCReturns.CameraFilterKeyframe]
CameraHint = typing.Union[_CameraHint_Prime.CameraHint, _CameraHint_Echoes.CameraHint, _CameraHint_Corruption.CameraHint, _CameraHint_DKCReturns.CameraHint]
CameraPitch = typing.Union[_CameraPitch_Echoes.CameraPitch, _CameraPitch_Corruption.CameraPitch]
CameraShaker = typing.Union[_CameraShaker_Prime.CameraShaker, _CameraShaker_Echoes.CameraShaker, _CameraShaker_Corruption.CameraShaker, _CameraShaker_DKCReturns.CameraShaker]
CameraWaypoint = typing.Union[_CameraWaypoint_Prime.CameraWaypoint, _CameraWaypoint_Echoes.CameraWaypoint]
CannonBall = typing.Union[_CannonBall_Echoes.CannonBall, _CannonBall_Corruption.CannonBall]
ChozoGhost = typing.Union[_ChozoGhost_Prime.ChozoGhost, _ChozoGhost_Echoes.ChozoGhost]
CinematicCamera = typing.Union[_CinematicCamera_Corruption.CinematicCamera, _CinematicCamera_DKCReturns.CinematicCamera]
ColorModulate = typing.Union[_ColorModulate_Prime.ColorModulate, _ColorModulate_Echoes.ColorModulate, _ColorModulate_Corruption.ColorModulate, _ColorModulate_DKCReturns.ColorModulate]
ConditionalRelay = typing.Union[_ConditionalRelay_Echoes.ConditionalRelay, _ConditionalRelay_Corruption.ConditionalRelay, _ConditionalRelay_DKCReturns.ConditionalRelay]
ControlHint = typing.Union[_ControlHint_Echoes.ControlHint, _ControlHint_Corruption.ControlHint]
ControllerAction = typing.Union[_ControllerAction_Prime.ControllerAction, _ControllerAction_Echoes.ControllerAction, _ControllerAction_Corruption.ControllerAction, _ControllerAction_DKCReturns.ControllerAction]
Counter = typing.Union[_Counter_Prime.Counter, _Counter_Echoes.Counter, _Counter_Corruption.Counter, _Counter_DKCReturns.Counter]
CoverPoint = typing.Union[_CoverPoint_Prime.CoverPoint, _CoverPoint_Echoes.CoverPoint, _CoverPoint_Corruption.CoverPoint]
DamageActor = typing.Union[_DamageActor_Echoes.DamageActor, _DamageActor_Corruption.DamageActor]
DamageableTrigger = typing.Union[_DamageableTrigger_Prime.DamageableTrigger, _DamageableTrigger_Echoes.DamageableTrigger, _DamageableTrigger_Corruption.DamageableTrigger, _DamageableTrigger_DKCReturns.DamageableTrigger]
DamageableTriggerOrientated = typing.Union[_DamageableTriggerOrientated_Echoes.DamageableTriggerOrientated, _DamageableTriggerOrientated_Corruption.DamageableTriggerOrientated, _DamageableTriggerOrientated_DKCReturns.DamageableTriggerOrientated]
DarkSamus = typing.Union[_DarkSamus_Echoes.DarkSamus, _DarkSamus_Corruption.DarkSamus]
Debris = typing.Union[_Debris_Prime.Debris, _Debris_Echoes.Debris, _Debris_Corruption.Debris, _Debris_DKCReturns.Debris]
DebrisExtended = typing.Union[_DebrisExtended_Prime.DebrisExtended, _DebrisExtended_Echoes.DebrisExtended]
DistanceFog = typing.Union[_DistanceFog_Prime.DistanceFog, _DistanceFog_Echoes.DistanceFog, _DistanceFog_Corruption.DistanceFog, _DistanceFog_DKCReturns.DistanceFog]
Dock = typing.Union[_Dock_Prime.Dock, _Dock_Echoes.Dock, _Dock_Corruption.Dock]
Door = typing.Union[_Door_Prime.Door, _Door_Echoes.Door, _Door_Corruption.Door]
DynamicLight = typing.Union[_DynamicLight_Echoes.DynamicLight, _DynamicLight_Corruption.DynamicLight, _DynamicLight_DKCReturns.DynamicLight]
Effect = typing.Union[_Effect_Prime.Effect, _Effect_Echoes.Effect, _Effect_Corruption.Effect, _Effect_DKCReturns.Effect]
ElectroMagneticPulse = typing.Union[_ElectroMagneticPulse_Prime.ElectroMagneticPulse, _ElectroMagneticPulse_Corruption.ElectroMagneticPulse]
ElitePirate = typing.Union[_ElitePirate_Prime.ElitePirate, _ElitePirate_Echoes.ElitePirate]
EnvFxDensityController = typing.Union[_EnvFxDensityController_Prime.EnvFxDensityController, _EnvFxDensityController_Echoes.EnvFxDensityController, _EnvFxDensityController_Corruption.EnvFxDensityController, _EnvFxDensityController_DKCReturns.EnvFxDensityController]
FalsePerspective = typing.Union[_FalsePerspective_Corruption.FalsePerspective, _FalsePerspective_DKCReturns.FalsePerspective]
FishCloud = typing.Union[_FishCloud_Prime.FishCloud, _FishCloud_Echoes.FishCloud, _FishCloud_Corruption.FishCloud]
FishCloudModifier = typing.Union[_FishCloudModifier_Prime.FishCloudModifier, _FishCloudModifier_Echoes.FishCloudModifier, _FishCloudModifier_Corruption.FishCloudModifier]
FlyerSwarm = typing.Union[_FlyerSwarm_Echoes.FlyerSwarm, _FlyerSwarm_Corruption.FlyerSwarm]
FlyingPirate = typing.Union[_FlyingPirate_Prime.FlyingPirate, _FlyingPirate_Echoes.FlyingPirate, _FlyingPirate_Corruption.FlyingPirate]
FogOverlay = typing.Union[_FogOverlay_Echoes.FogOverlay, _FogOverlay_Corruption.FogOverlay, _FogOverlay_DKCReturns.FogOverlay]
FogVolume = typing.Union[_FogVolume_Prime.FogVolume, _FogVolume_Echoes.FogVolume, _FogVolume_Corruption.FogVolume, _FogVolume_DKCReturns.FogVolume]
GeneratedObjectDeleter = typing.Union[_GeneratedObjectDeleter_Corruption.GeneratedObjectDeleter, _GeneratedObjectDeleter_DKCReturns.GeneratedObjectDeleter]
Generator = typing.Union[_Generator_Prime.Generator, _Generator_Echoes.Generator, _Generator_Corruption.Generator, _Generator_DKCReturns.Generator]
GrapplePoint = typing.Union[_GrapplePoint_Prime.GrapplePoint, _GrapplePoint_Echoes.GrapplePoint, _GrapplePoint_Corruption.GrapplePoint]
GuiMenu = typing.Union[_GuiMenu_Echoes.GuiMenu, _GuiMenu_Corruption.GuiMenu, _GuiMenu_DKCReturns.GuiMenu]
GuiScreen = typing.Union[_GuiScreen_Echoes.GuiScreen, _GuiScreen_Corruption.GuiScreen]
GuiSlider = typing.Union[_GuiSlider_Echoes.GuiSlider, _GuiSlider_Corruption.GuiSlider, _GuiSlider_DKCReturns.GuiSlider]
GuiWidget = typing.Union[_GuiWidget_Echoes.GuiWidget, _GuiWidget_Corruption.GuiWidget, _GuiWidget_DKCReturns.GuiWidget]
GunTurretBase = typing.Union[_GunTurretBase_Echoes.GunTurretBase, _GunTurretBase_Corruption.GunTurretBase]
GunTurretTop = typing.Union[_GunTurretTop_Echoes.GunTurretTop, _GunTurretTop_Corruption.GunTurretTop]
HUDHint = typing.Union[_HUDHint_Echoes.HUDHint, _HUDHint_Corruption.HUDHint]
HUDMemo = typing.Union[_HUDMemo_Prime.HUDMemo, _HUDMemo_Echoes.HUDMemo, _HUDMemo_Corruption.HUDMemo]
LODController = typing.Union[_LODController_Corruption.LODController, _LODController_DKCReturns.LODController]
LightVolume = typing.Union[_LightVolume_Corruption.LightVolume, _LightVolume_DKCReturns.LightVolume]
MemoryRelay = typing.Union[_MemoryRelay_Prime.MemoryRelay, _MemoryRelay_Echoes.MemoryRelay, _MemoryRelay_Corruption.MemoryRelay, _MemoryRelay_DKCReturns.MemoryRelay]
Metaree = typing.Union[_Metaree_Echoes.Metaree, _Metaree_Corruption.Metaree]
MetroidAlpha = typing.Union[_MetroidAlpha_Prime.MetroidAlpha, _MetroidAlpha_Echoes.MetroidAlpha]
Midi = typing.Union[_Midi_Prime.Midi, _Midi_Echoes.Midi]
MinorIng = typing.Union[_MinorIng_Echoes.MinorIng, _MinorIng_Corruption.MinorIng]
MultiModelActor = typing.Union[_MultiModelActor_Corruption.MultiModelActor, _MultiModelActor_DKCReturns.MultiModelActor]
MysteryFlyer = typing.Union[_MysteryFlyer_Echoes.MysteryFlyer, _MysteryFlyer_Corruption.MysteryFlyer]
OptionalAreaAsset = typing.Union[_OptionalAreaAsset_Corruption.OptionalAreaAsset, _OptionalAreaAsset_DKCReturns.OptionalAreaAsset]
Parasite = typing.Union[_Parasite_Prime.Parasite, _Parasite_Echoes.Parasite, _Parasite_Corruption.Parasite]
PathCamera = typing.Union[_PathCamera_Prime.PathCamera, _PathCamera_Echoes.PathCamera]
PathControl = typing.Union[_PathControl_Corruption.PathControl, _PathControl_DKCReturns.PathControl]
PathMeshCtrl = typing.Union[_PathMeshCtrl_Echoes.PathMeshCtrl, _PathMeshCtrl_Corruption.PathMeshCtrl]
Pickup = typing.Union[_Pickup_Prime.Pickup, _Pickup_Echoes.Pickup, _Pickup_Corruption.Pickup, _Pickup_DKCReturns.Pickup]
PickupGenerator = typing.Union[_PickupGenerator_Prime.PickupGenerator, _PickupGenerator_Echoes.PickupGenerator]
PillBug = typing.Union[_PillBug_Echoes.PillBug, _PillBug_Corruption.PillBug]
PlantScarabSwarm = typing.Union[_PlantScarabSwarm_Echoes.PlantScarabSwarm, _PlantScarabSwarm_Corruption.PlantScarabSwarm]
Platform = typing.Union[_Platform_Prime.Platform, _Platform_Echoes.Platform, _Platform_Corruption.Platform, _Platform_DKCReturns.Platform]
PlayerActor = typing.Union[_PlayerActor_Prime.PlayerActor, _PlayerActor_Echoes.PlayerActor, _PlayerActor_Corruption.PlayerActor, _PlayerActor_DKCReturns.PlayerActor]
PlayerHint = typing.Union[_PlayerHint_Prime.PlayerHint, _PlayerHint_Echoes.PlayerHint, _PlayerHint_Corruption.PlayerHint]
PlayerStateChange = typing.Union[_PlayerStateChange_Prime.PlayerStateChange, _PlayerStateChange_Echoes.PlayerStateChange]
PointOfInterest = typing.Union[_PointOfInterest_Prime.PointOfInterest, _PointOfInterest_Echoes.PointOfInterest, _PointOfInterest_Corruption.PointOfInterest]
PositionRelay = typing.Union[_PositionRelay_Corruption.PositionRelay, _PositionRelay_DKCReturns.PositionRelay]
PuddleSpore = typing.Union[_PuddleSpore_Prime.PuddleSpore, _PuddleSpore_Echoes.PuddleSpore]
Puffer = typing.Union[_Puffer_Prime.Puffer, _Puffer_Echoes.Puffer, _Puffer_Corruption.Puffer]
RadialDamage = typing.Union[_RadialDamage_Prime.RadialDamage, _RadialDamage_Echoes.RadialDamage, _RadialDamage_Corruption.RadialDamage, _RadialDamage_DKCReturns.RadialDamage]
RandomRelay = typing.Union[_RandomRelay_Prime.RandomRelay, _RandomRelay_Echoes.RandomRelay, _RandomRelay_Corruption.RandomRelay]
Relay = typing.Union[_Relay_Prime.Relay, _Relay_Echoes.Relay, _Relay_Corruption.Relay, _Relay_DKCReturns.Relay]
Repulsor = typing.Union[_Repulsor_Prime.Repulsor, _Repulsor_Echoes.Repulsor, _Repulsor_Corruption.Repulsor]
Ripper = typing.Union[_Ripper_Prime.Ripper, _Ripper_Echoes.Ripper]
Ripple = typing.Union[_Ripple_Prime.Ripple, _Ripple_Echoes.Ripple, _Ripple_Corruption.Ripple]
RoomAcoustics = typing.Union[_RoomAcoustics_Prime.RoomAcoustics, _RoomAcoustics_Echoes.RoomAcoustics, _RoomAcoustics_Corruption.RoomAcoustics]
RumbleEffect = typing.Union[_RumbleEffect_Prime.RumbleEffect, _RumbleEffect_Echoes.RumbleEffect, _RumbleEffect_Corruption.RumbleEffect, _RumbleEffect_DKCReturns.RumbleEffect]
ScriptLayerController = typing.Union[_ScriptLayerController_Echoes.ScriptLayerController, _ScriptLayerController_Corruption.ScriptLayerController, _ScriptLayerController_DKCReturns.ScriptLayerController]
SequenceTimer = typing.Union[_SequenceTimer_Echoes.SequenceTimer, _SequenceTimer_Corruption.SequenceTimer, _SequenceTimer_DKCReturns.SequenceTimer]
ShadowProjector = typing.Union[_ShadowProjector_Prime.ShadowProjector, _ShadowProjector_Echoes.ShadowProjector, _ShadowProjector_Corruption.ShadowProjector, _ShadowProjector_DKCReturns.ShadowProjector]
SkyRipple = typing.Union[_SkyRipple_Echoes.SkyRipple, _SkyRipple_Corruption.SkyRipple]
SkyboxModInca = typing.Union[_SkyboxModInca_Corruption.SkyboxModInca, _SkyboxModInca_DKCReturns.SkyboxModInca]
SnakeWeedSwarm = typing.Union[_SnakeWeedSwarm_Prime.SnakeWeedSwarm, _SnakeWeedSwarm_Echoes.SnakeWeedSwarm]
Sound = typing.Union[_Sound_Prime.Sound, _Sound_Echoes.Sound, _Sound_Corruption.Sound, _Sound_DKCReturns.Sound]
SoundModifier = typing.Union[_SoundModifier_Echoes.SoundModifier, _SoundModifier_Corruption.SoundModifier, _SoundModifier_DKCReturns.SoundModifier]
SpacePirate = typing.Union[_SpacePirate_Prime.SpacePirate, _SpacePirate_Echoes.SpacePirate, _SpacePirate_Corruption.SpacePirate]
SpankWeed = typing.Union[_SpankWeed_Prime.SpankWeed, _SpankWeed_Echoes.SpankWeed]
SpawnPoint = typing.Union[_SpawnPoint_Prime.SpawnPoint, _SpawnPoint_Echoes.SpawnPoint, _SpawnPoint_Corruption.SpawnPoint, _SpawnPoint_DKCReturns.SpawnPoint]
SpecialFunction = typing.Union[_SpecialFunction_Prime.SpecialFunction, _SpecialFunction_Echoes.SpecialFunction, _SpecialFunction_Corruption.SpecialFunction, _SpecialFunction_DKCReturns.SpecialFunction]
SpiderBallAttractionSurface = typing.Union[_SpiderBallAttractionSurface_Prime.SpiderBallAttractionSurface, _SpiderBallAttractionSurface_Echoes.SpiderBallAttractionSurface, _SpiderBallAttractionSurface_Corruption.SpiderBallAttractionSurface]
SpiderBallWaypoint = typing.Union[_SpiderBallWaypoint_Prime.SpiderBallWaypoint, _SpiderBallWaypoint_Echoes.SpiderBallWaypoint, _SpiderBallWaypoint_Corruption.SpiderBallWaypoint]
SpindleCamera = typing.Union[_SpindleCamera_Prime.SpindleCamera, _SpindleCamera_Echoes.SpindleCamera]
Spinner = typing.Union[_Spinner_Echoes.Spinner, _Spinner_Corruption.Spinner, _Spinner_DKCReturns.Spinner]
Steam = typing.Union[_Steam_Prime.Steam, _Steam_Echoes.Steam, _Steam_Corruption.Steam]
StreamedAudio = typing.Union[_StreamedAudio_Prime.StreamedAudio, _StreamedAudio_Echoes.StreamedAudio, _StreamedAudio_Corruption.StreamedAudio, _StreamedAudio_DKCReturns.StreamedAudio]
StreamedMovie = typing.Union[_StreamedMovie_Echoes.StreamedMovie, _StreamedMovie_Corruption.StreamedMovie, _StreamedMovie_DKCReturns.StreamedMovie]
Subtitles = typing.Union[_Subtitles_Corruption.Subtitles, _Subtitles_DKCReturns.Subtitles]
SurfaceControl = typing.Union[_SurfaceControl_Corruption.SurfaceControl, _SurfaceControl_DKCReturns.SurfaceControl]
Switch = typing.Union[_Switch_Prime.Switch, _Switch_Echoes.Switch, _Switch_Corruption.Switch, _Switch_DKCReturns.Switch]
TargetingPoint = typing.Union[_TargetingPoint_Prime.TargetingPoint, _TargetingPoint_Echoes.TargetingPoint, _TargetingPoint_Corruption.TargetingPoint]
TeamAI = typing.Union[_TeamAI_Echoes.TeamAI, _TeamAI_Corruption.TeamAI]
TextPane = typing.Union[_TextPane_Echoes.TextPane, _TextPane_Corruption.TextPane, _TextPane_DKCReturns.TextPane]
TimeKeyframe = typing.Union[_TimeKeyframe_Echoes.TimeKeyframe, _TimeKeyframe_Corruption.TimeKeyframe, _TimeKeyframe_DKCReturns.TimeKeyframe]
Timer = typing.Union[_Timer_Prime.Timer, _Timer_Echoes.Timer, _Timer_Corruption.Timer, _Timer_DKCReturns.Timer]
Trigger = typing.Union[_Trigger_Prime.Trigger, _Trigger_Echoes.Trigger, _Trigger_Corruption.Trigger, _Trigger_DKCReturns.Trigger]
Tryclops = typing.Union[_Tryclops_Prime.Tryclops, _Tryclops_Echoes.Tryclops]
VisorFlare = typing.Union[_VisorFlare_Prime.VisorFlare, _VisorFlare_Echoes.VisorFlare, _VisorFlare_Corruption.VisorFlare]
VisorGoo = typing.Union[_VisorGoo_Prime.VisorGoo, _VisorGoo_Echoes.VisorGoo, _VisorGoo_Corruption.VisorGoo]
WallCrawlerSwarm = typing.Union[_WallCrawlerSwarm_Prime.WallCrawlerSwarm, _WallCrawlerSwarm_Corruption.WallCrawlerSwarm]
Water = typing.Union[_Water_Prime.Water, _Water_Echoes.Water, _Water_Corruption.Water]
Waypoint = typing.Union[_Waypoint_Prime.Waypoint, _Waypoint_Echoes.Waypoint, _Waypoint_Corruption.Waypoint, _Waypoint_DKCReturns.Waypoint]
WorldAttributes = typing.Union[_WorldAttributes_Corruption.WorldAttributes, _WorldAttributes_DKCReturns.WorldAttributes]
WorldLightFader = typing.Union[_WorldLightFader_Prime.WorldLightFader, _WorldLightFader_Echoes.WorldLightFader, _WorldLightFader_Corruption.WorldLightFader, _WorldLightFader_DKCReturns.WorldLightFader]
WorldTeleporter = typing.Union[_WorldTeleporter_Prime.WorldTeleporter, _WorldTeleporter_Echoes.WorldTeleporter, _WorldTeleporter_Corruption.WorldTeleporter]
