
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T13:47:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "72111a266cd41af7778ac19f68af986bc267f2d3",
 "version": "1.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
