# coding: utf-8

"""
    DLCM-Solution

    DLCM application wrapping all modules, All-In-One  # noqa: E501

    The version of the OpenAPI document: 2.1.1
    Contact: eresearch-opensource@unige.ch
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dlcmapi_client.configuration import Configuration


class Collection(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data': 'object',
        'links': 'object',
        'page': 'Page'
    }

    attribute_map = {
        'data': '_data',
        'links': '_links',
        'page': '_page'
    }

    def __init__(self, data=None, links=None, page=None, local_vars_configuration=None):  # noqa: E501
        """Collection - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._data = None
        self._links = None
        self._page = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if links is not None:
            self.links = links
        if page is not None:
            self.page = page

    @property
    def data(self):
        """Gets the data of this Collection.  # noqa: E501

        List the collection of the resources  # noqa: E501

        :return: The data of this Collection.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Collection.

        List the collection of the resources  # noqa: E501

        :param data: The data of this Collection.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def links(self):
        """Gets the links of this Collection.  # noqa: E501

        All links available on the resource  # noqa: E501

        :return: The links of this Collection.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Collection.

        All links available on the resource  # noqa: E501

        :param links: The links of this Collection.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def page(self):
        """Gets the page of this Collection.  # noqa: E501


        :return: The page of this Collection.  # noqa: E501
        :rtype: Page
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this Collection.


        :param page: The page of this Collection.  # noqa: E501
        :type: Page
        """

        self._page = page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Collection):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Collection):
            return True

        return self.to_dict() != other.to_dict()
