from os import getenv

from dotenv import load_dotenv

load_dotenv(".env")


class Var:
    API_HASH = getenv("API_HASH")
    API_ID = int(getenv("API_ID", ""))
    BOT_TOKEN = getenv("BOT_TOKEN", "")
    BLACKLIST_CHAT = getenv("BLACKLIST_CHAT", None)
    if not BLACKLIST_CHAT:
        BLACKLIST_CHAT = [-1001473548283, -1001675396283]
    LOG_CHAT = int(getenv("LOG_CHAT") or 0)
    VERSION = "0.1"
    BRANCH = "main"
    HNDLR = getenv("HNDLR", [".", "!", "*", "^", "-", "?"])
    DB_URL = getenv("DATABASE_URL", "")
    GIT_TOKEN = getenv("GIT_TOKEN", "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")
    HEROKU_API_KEY = getenv("HEROKU_API_KEY", None)
    HEROKU_APP_NAME = getenv("HEROKU_APP_NAME", None)
    MONGO_URI = getenv("MONGO_URI", None)
    NO_LOAD = [int(x) for x in getenv("NO_LOAD", "").split()]
    REM_BG_API_KEY = getenv("REM_BG_API_KEY", "WEnHwQnst3E2HzjGgwmy4UpB")
    REPO_URL = getenv("REPO_URL", "https://github.com/YinsXd/Ubot")
    SESSION_1 = getenv("SESSION_1", "")
    SESSION_2 = getenv("SESSION_2", "")
    SESSION_3 = getenv("SESSION_3", "")
    SESSION_4 = getenv("SESSION_4", "")
    SESSION_5 = getenv("SESSION_5", "")
    SESSION_6 = getenv("SESSION_6", "")
    SESSION_7 = getenv("SESSION_7", "")
    SESSION_8 = getenv("SESSION_8", "")
    SESSION_9 = getenv("SESSION_9", "")
    SESSION_10 = getenv("SESSION_10", "")
    SESSION_11 = getenv("SESSION_11", "")
    SESSION_12 = getenv("SESSION_12", "")
    SESSION_13 = getenv("SESSION_13", "")
    SESSION_14 = getenv("SESSION_14", "")
    SESSION_15 = getenv("SESSION_15", "")
    SESSION_16 = getenv("SESSION_16", "")
    SESSION_17 = getenv("SESSION_17", "")
    SESSION_18 = getenv("SESSION_18", "")
    SESSION_19 = getenv("SESSION_19", "")
    SESSION_20 = getenv("SESSION_20", "")
    SESSION_21 = getenv("SESSION_21", "")
    SESSION_22 = getenv("SESSION_22", "")
    SESSION_23 = getenv("SESSION_23", "")
    SESSION_24 = getenv("SESSION_24", "")
    SESSION_25 = getenv("SESSION_25", "")
    SESSION_26 = getenv("SESSION_26", "")
    SESSION_27 = getenv("SESSION_27", "")
    SESSION_28 = getenv("SESSION_28", "")
    SESSION_29 = getenv("SESSION_29", "")
    SESSION_30 = getenv("SESSION_30", "")
    SESSION_31 = getenv("SESSION_31", "")
    SESSION_32 = getenv("SESSION_32", "")
    SESSION_33 = getenv("SESSION_33", "")
    SESSION_34 = getenv("SESSION_34", "")
    SESSION_35 = getenv("SESSION_35", "")
    SESSION_36 = getenv("SESSION_36", "")
    SESSION_37 = getenv("SESSION_37", "")
    SESSION_38 = getenv("SESSION_38", "")
    SESSION_39 = getenv("SESSION_39", "")
    SESSION_40 = getenv("SESSION_40", "")
    SESSION_41 = getenv("SESSION_41", "")
    SESSION_42 = getenv("SESSION_42", "")
    SESSION_43 = getenv("SESSION_43", "")
    SESSION_44 = getenv("SESSION_44", "")
    SESSION_45 = getenv("SESSION_45", "")
    SESSION_46 = getenv("SESSION_46", "")
    SESSION_47 = getenv("SESSION_47", "")
    SESSION_48 = getenv("SESSION_48", "")
    SESSION_49 = getenv("SESSION_49", "")
    SESSION_50 = getenv("SESSION_50", "")
    TEMP_DOWNLOAD_DIRECTORY = getenv("TMP_DOWNLOAD_DIRECTORY", "./downloads/")
    TZ = getenv("TZ", "Asia/Jakarta")
