
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T14:43:59+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8fbb17e7f96d6181fd3bd2852af98097fb9b0a9",
 "version": "2.10.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
