
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T10:06:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "84db397dec110fadcf1aef392189937d3fe6e087",
 "version": "1.17.1.post0.dev348"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
