# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import collibra_data_classification
from collibra_data_classification.paths.data_classification_classifications_bulk import get  # noqa: E501
from collibra_data_classification import configuration, schemas, api_client

from .. import ApiTestMixin


class TestDataClassificationClassificationsBulk(ApiTestMixin, unittest.TestCase):
    """
    DataClassificationClassificationsBulk unit test stubs
        Finds Classifications  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
