
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T07:38:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dbcb45bc3fa667147ed93e05b934bd65daa345c",
 "version": "1.17.1.post0.dev327"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
