PASS = 'PASS'
FAIL = 'FAIL'
ABORT = 'ABORT'
MODE_DEBUG = 'DEBUG'
MODE_PROD = 'PROD'
FINALIZATION = 'FINALIZATION'

CONTAINER = {}
SUPER_CONTAINER = {}
SUPER_SYNC_GROUPS = {}
SYNC_GROUPS = {}
RUNTIME = {}
