VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('09')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('35')
MAJOR_VERSION = 0
MINOR_VERSION = 23
PATCH_VERSION = 202211091335
version_date = '2022/11/09 13:35'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
