VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('06')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 0
MINOR_VERSION = 21
PATCH_VERSION = 202211062137
version_date = '2022/11/06 21:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
