
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T09:03:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8760008f9f52f1aed11e175aa11619253b30db6",
 "version": "1.17.1.post0.dev339"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
