# coding: utf-8

"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_core.paths.navigation_most_viewed.get import FindMostViewedAssets
from collibra_core.paths.navigation_recently_viewed.get import FindRecentlyViewedAssets


class NavigationStatisticsApi(
    FindMostViewedAssets,
    FindRecentlyViewedAssets,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
