# coding: utf-8

"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_core.paths.scopes.post import AddScope
from collibra_core.paths.scopes_scope_id.patch import ChangeScope
from collibra_core.paths.scopes.get import GetAllScopes
from collibra_core.paths.scopes_scope_id.get import GetScope
from collibra_core.paths.scopes_scope_id.delete import RemoveScope


class ScopesApi(
    AddScope,
    ChangeScope,
    GetAllScopes,
    GetScope,
    RemoveScope,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
