# coding: utf-8

"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_core.paths.jobs_job_id_canceled.post import CancelJob
from collibra_core.paths.jobs.get import FindJobs
from collibra_core.paths.jobs_job_id.get import GetJob


class JobsApi(
    CancelJob,
    FindJobs,
    GetJob,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
