
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T11:03:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e40dccf0e3e82d2acbdd42fad61bdf88ada62aca",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
