{
 "title": "vSphere - Host details",
 "description": "Dashboard for ESXi host metrics in a VMware vSphere environment",
 "tags": [
  "telegraf",
  "vsphere"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vc",
    "label": "vCenter",
    "query": "show tag values with key = \"vcenter\""
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"clustername\" where \"vcenter\" =~/$vc/"
   },
   {
    "name": "host",
    "label": "ESXi",
    "query": "show tag values with key = \"esxhostname\" where \"clustername\" =~/$cluster/ and \"vcenter\" =~/$vc/"
   },
   {
    "name": "time",
    "label": "Time",
    "query": "20s,1m,5m,15m,30m,1h,12h,24h,1w,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Details - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "vsphere_host_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"vmname\")) FROM (SELECT \"usage_average\", \"vmname\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter AND \"esxhostname\" =~ /$host/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Datastores",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"dsname\")) FROM (SELECT \"read_average\", \"dsname\" FROM  \"vsphere_host_datastore\" WHERE $timeFilter AND \"esxhostname\" =~ /$host/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NET",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Storage Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_datastore",
     "select": [
      [
       { "params": [ "maxTotalLatency_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Consumed vs Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "consumed_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consumed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "NET Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "NET Transmit / Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "receive" ], "type": "alias" }
      ],
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "transmit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}