
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T23:30:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "54a5888d7c7864f38e1ca4087e479c8073150219",
 "version": "0.0.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
