# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry.v0 import bodies_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2
from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


class BodiesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllBodies = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetAllBodies',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetAllBodiesResponse.FromString,
        )
    self.GetBody = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetBody',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.FromString,
        )
    self.GetAssignedMaterial = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetAssignedMaterial',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Material.FromString,
        )
    self.SetAssignedMaterial = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/SetAssignedMaterial',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.SetAssignedMaterialRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.SetAssignedMaterialResponse.FromString,
        )
    self.Translate = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/Translate',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.TranslateRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.GetFaces = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetFaces',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetFacesResponse.FromString,
        )
    self.GetEdges = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetEdges',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetEdgesResponse.FromString,
        )
    self.GetName = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetName',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetNameResponse.FromString,
        )
    self.CreateBodyFromFace = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/CreateBodyFromFace',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateBodyFromFaceRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.FromString,
        )
    self.CreateExtrudedBodyFromFaceProfile = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/CreateExtrudedBodyFromFaceProfile',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateExtrudedBodyFromFaceProfileRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.FromString,
        )
    self.Delete = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/Delete',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.CreatePlanarBody = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/CreatePlanarBody',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreatePlanarBodyRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.FromString,
        )
    self.CreateExtrudedBody = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/CreateExtrudedBody',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateExtrudedBodyRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.FromString,
        )
    self.GetVolume = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetVolume',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetVolumeResponse.FromString,
        )
    self.GetBodyTessellation = channel.unary_unary(
        '/ansys.api.geometry.v0.Bodies/GetBodyTessellation',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetBodyTessellationResponse.FromString,
        )


class BodiesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllBodies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBody(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssignedMaterial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetAssignedMaterial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Translate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFaces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEdges(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBodyFromFace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateExtrudedBodyFromFaceProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePlanarBody(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateExtrudedBody(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVolume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBodyTessellation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BodiesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllBodies': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllBodies,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetAllBodiesResponse.SerializeToString,
      ),
      'GetBody': grpc.unary_unary_rpc_method_handler(
          servicer.GetBody,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.SerializeToString,
      ),
      'GetAssignedMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssignedMaterial,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Material.SerializeToString,
      ),
      'SetAssignedMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.SetAssignedMaterial,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.SetAssignedMaterialRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.SetAssignedMaterialResponse.SerializeToString,
      ),
      'Translate': grpc.unary_unary_rpc_method_handler(
          servicer.Translate,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.TranslateRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'GetFaces': grpc.unary_unary_rpc_method_handler(
          servicer.GetFaces,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetFacesResponse.SerializeToString,
      ),
      'GetEdges': grpc.unary_unary_rpc_method_handler(
          servicer.GetEdges,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetEdgesResponse.SerializeToString,
      ),
      'GetName': grpc.unary_unary_rpc_method_handler(
          servicer.GetName,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetNameResponse.SerializeToString,
      ),
      'CreateBodyFromFace': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBodyFromFace,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateBodyFromFaceRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.SerializeToString,
      ),
      'CreateExtrudedBodyFromFaceProfile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateExtrudedBodyFromFaceProfile,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateExtrudedBodyFromFaceProfileRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'CreatePlanarBody': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePlanarBody,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreatePlanarBodyRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.SerializeToString,
      ),
      'CreateExtrudedBody': grpc.unary_unary_rpc_method_handler(
          servicer.CreateExtrudedBody,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.CreateExtrudedBodyRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Body.SerializeToString,
      ),
      'GetVolume': grpc.unary_unary_rpc_method_handler(
          servicer.GetVolume,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetVolumeResponse.SerializeToString,
      ),
      'GetBodyTessellation': grpc.unary_unary_rpc_method_handler(
          servicer.GetBodyTessellation,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.BodyIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_bodies__pb2.GetBodyTessellationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.geometry.v0.Bodies', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
