# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry.v0 import commands_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2
from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


class CommandsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProjectCurves = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/ProjectCurves',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ProjectCurvesRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ProjectCurvesResponse.FromString,
        )
    self.ImprintCurves = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/ImprintCurves',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ImprintCurvesRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ImprintCurvesResponse.FromString,
        )
    self.PowerSelectFacesByAreaRange = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/PowerSelectFacesByAreaRange',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.PowerSelectFacesByAreaRangeRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.PowerSelectFacesByAreaRangeResponse.FromString,
        )
    self.CreateBeamCircularProfile = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateBeamCircularProfile',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamCircularProfileRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamCircularProfileResponse.FromString,
        )
    self.CreateBeamBodyLine = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateBeamBodyLine',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLineRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLineResponse.FromString,
        )
    self.CreateBeamBodyLines = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateBeamBodyLines',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLinesRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLinesResponse.FromString,
        )
    self.GetRootComponent = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/GetRootComponent',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.GetRootComponentResponse.FromString,
        )
    self.FillFaces = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/FillFaces',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.FillFacesRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.CreateDesignPoint = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateDesignPoint',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointResponse.FromString,
        )
    self.CreateDesignPoints = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateDesignPoints',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointsRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointsResponse.FromString,
        )
    self.CreateDesignCurvesFromProfile = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateDesignCurvesFromProfile',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignCurvesFromProfileRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignCurvesFromProfileResponse.FromString,
        )
    self.AssignMidSurfaceThickness = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/AssignMidSurfaceThickness',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.AssignMidSurfaceThicknessRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.AssignMidSurfaceOffsetType = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/AssignMidSurfaceOffsetType',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.AssignMidSurfaceOffsetTypeRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.DownloadFile = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/DownloadFile',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.DownloadFileResponse.FromString,
        )
    self.DownloadFileStream = channel.unary_stream(
        '/ansys.api.geometry.v0.Commands/DownloadFileStream',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.DownloadFileStreamResponse.FromString,
        )
    self.CreateSphere = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateSphere',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateSphereRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateSphereResponse.FromString,
        )
    self.CreateTorus = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/CreateTorus',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateTorusRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateTorusResponse.FromString,
        )
    self.DeleteBeam = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/DeleteBeam',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.EntityIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )
    self.DeleteBeamProfile = channel.unary_unary(
        '/ansys.api.geometry.v0.Commands/DeleteBeamProfile',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.EntityIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
        )


class CommandsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProjectCurves(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImprintCurves(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PowerSelectFacesByAreaRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBeamCircularProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBeamBodyLine(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBeamBodyLines(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRootComponent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FillFaces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateDesignPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateDesignPoints(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateDesignCurvesFromProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AssignMidSurfaceThickness(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AssignMidSurfaceOffsetType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadFileStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSphere(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTorus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBeam(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBeamProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommandsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProjectCurves': grpc.unary_unary_rpc_method_handler(
          servicer.ProjectCurves,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ProjectCurvesRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ProjectCurvesResponse.SerializeToString,
      ),
      'ImprintCurves': grpc.unary_unary_rpc_method_handler(
          servicer.ImprintCurves,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ImprintCurvesRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.ImprintCurvesResponse.SerializeToString,
      ),
      'PowerSelectFacesByAreaRange': grpc.unary_unary_rpc_method_handler(
          servicer.PowerSelectFacesByAreaRange,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.PowerSelectFacesByAreaRangeRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.PowerSelectFacesByAreaRangeResponse.SerializeToString,
      ),
      'CreateBeamCircularProfile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBeamCircularProfile,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamCircularProfileRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamCircularProfileResponse.SerializeToString,
      ),
      'CreateBeamBodyLine': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBeamBodyLine,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLineRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLineResponse.SerializeToString,
      ),
      'CreateBeamBodyLines': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBeamBodyLines,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLinesRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateBeamBodyLinesResponse.SerializeToString,
      ),
      'GetRootComponent': grpc.unary_unary_rpc_method_handler(
          servicer.GetRootComponent,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.GetRootComponentResponse.SerializeToString,
      ),
      'FillFaces': grpc.unary_unary_rpc_method_handler(
          servicer.FillFaces,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.FillFacesRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'CreateDesignPoint': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDesignPoint,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointResponse.SerializeToString,
      ),
      'CreateDesignPoints': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDesignPoints,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointsRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignPointsResponse.SerializeToString,
      ),
      'CreateDesignCurvesFromProfile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDesignCurvesFromProfile,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignCurvesFromProfileRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateDesignCurvesFromProfileResponse.SerializeToString,
      ),
      'AssignMidSurfaceThickness': grpc.unary_unary_rpc_method_handler(
          servicer.AssignMidSurfaceThickness,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.AssignMidSurfaceThicknessRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'AssignMidSurfaceOffsetType': grpc.unary_unary_rpc_method_handler(
          servicer.AssignMidSurfaceOffsetType,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.AssignMidSurfaceOffsetTypeRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'DownloadFile': grpc.unary_unary_rpc_method_handler(
          servicer.DownloadFile,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.DownloadFileResponse.SerializeToString,
      ),
      'DownloadFileStream': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadFileStream,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.DownloadFileStreamResponse.SerializeToString,
      ),
      'CreateSphere': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSphere,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateSphereRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateSphereResponse.SerializeToString,
      ),
      'CreateTorus': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTorus,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateTorusRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.CreateTorusResponse.SerializeToString,
      ),
      'DeleteBeam': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBeam,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.EntityIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
      'DeleteBeamProfile': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBeamProfile,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_commands__pb2.EntityIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.geometry.v0.Commands', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
