# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry.v0 import coordinatesystems_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2
from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


class CoordinateSystemsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCoordinateSystem = channel.unary_unary(
        '/ansys.api.geometry.v0.CoordinateSystems/GetCoordinateSystem',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.GetCoordinateSystemIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.CoordinateSystem.FromString,
        )
    self.GetAllCoordinateSystems = channel.unary_unary(
        '/ansys.api.geometry.v0.CoordinateSystems/GetAllCoordinateSystems',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.GetAllCoordinateSystemsResponse.FromString,
        )
    self.CreateCoordinateSystem = channel.unary_unary(
        '/ansys.api.geometry.v0.CoordinateSystems/CreateCoordinateSystem',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.CreateCoordinateSystemRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.CoordinateSystem.FromString,
        )


class CoordinateSystemsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCoordinateSystem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllCoordinateSystems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateCoordinateSystem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoordinateSystemsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCoordinateSystem': grpc.unary_unary_rpc_method_handler(
          servicer.GetCoordinateSystem,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.GetCoordinateSystemIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.CoordinateSystem.SerializeToString,
      ),
      'GetAllCoordinateSystems': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllCoordinateSystems,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Empty.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.GetAllCoordinateSystemsResponse.SerializeToString,
      ),
      'CreateCoordinateSystem': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCoordinateSystem,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_coordinatesystems__pb2.CreateCoordinateSystemRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.CoordinateSystem.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.geometry.v0.CoordinateSystems', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
