# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/geometry/v0/designs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansys/api/geometry/v0/designs.proto',
  package='ansys.api.geometry.v0',
  syntax='proto3',
  serialized_options=_b('\252\002\025Ansys.Api.Geometry.V0'),
  serialized_pb=_b('\n#ansys/api/geometry/v0/designs.proto\x12\x15\x61nsys.api.geometry.v0\x1a\"ansys/api/geometry/v0/models.proto\" \n\x10NewDesignRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x06\x44\x65sign\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\")\n\x15SaveAsDocumentRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"$\n\x16SaveAsDocumentResponse\x12\n\n\x02id\x18\x01 \x01(\t\"N\n\x13\x45xportDesignRequest\x12\x37\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\'.ansys.api.geometry.v0.PartExportFormat\"$\n\x14\x45xportDesignResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xa8\x02\n\x07\x44\x65signs\x12M\n\x03New\x12\'.ansys.api.geometry.v0.NewDesignRequest\x1a\x1d.ansys.api.geometry.v0.Design\x12\x65\n\x06SaveAs\x12,.ansys.api.geometry.v0.SaveAsDocumentRequest\x1a-.ansys.api.geometry.v0.SaveAsDocumentResponse\x12g\n\x0c\x45xportDesign\x12*.ansys.api.geometry.v0.ExportDesignRequest\x1a+.ansys.api.geometry.v0.ExportDesignResponseB\x18\xaa\x02\x15\x41nsys.Api.Geometry.V0b\x06proto3')
  ,
  dependencies=[ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.DESCRIPTOR,])




_NEWDESIGNREQUEST = _descriptor.Descriptor(
  name='NewDesignRequest',
  full_name='ansys.api.geometry.v0.NewDesignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.geometry.v0.NewDesignRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=130,
)


_DESIGN = _descriptor.Descriptor(
  name='Design',
  full_name='ansys.api.geometry.v0.Design',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ansys.api.geometry.v0.Design.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.geometry.v0.Design.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=166,
)


_SAVEASDOCUMENTREQUEST = _descriptor.Descriptor(
  name='SaveAsDocumentRequest',
  full_name='ansys.api.geometry.v0.SaveAsDocumentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='ansys.api.geometry.v0.SaveAsDocumentRequest.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=209,
)


_SAVEASDOCUMENTRESPONSE = _descriptor.Descriptor(
  name='SaveAsDocumentResponse',
  full_name='ansys.api.geometry.v0.SaveAsDocumentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ansys.api.geometry.v0.SaveAsDocumentResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=247,
)


_EXPORTDESIGNREQUEST = _descriptor.Descriptor(
  name='ExportDesignRequest',
  full_name='ansys.api.geometry.v0.ExportDesignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='ansys.api.geometry.v0.ExportDesignRequest.format', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=327,
)


_EXPORTDESIGNRESPONSE = _descriptor.Descriptor(
  name='ExportDesignResponse',
  full_name='ansys.api.geometry.v0.ExportDesignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ansys.api.geometry.v0.ExportDesignResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=365,
)

_EXPORTDESIGNREQUEST.fields_by_name['format'].enum_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._PARTEXPORTFORMAT
DESCRIPTOR.message_types_by_name['NewDesignRequest'] = _NEWDESIGNREQUEST
DESCRIPTOR.message_types_by_name['Design'] = _DESIGN
DESCRIPTOR.message_types_by_name['SaveAsDocumentRequest'] = _SAVEASDOCUMENTREQUEST
DESCRIPTOR.message_types_by_name['SaveAsDocumentResponse'] = _SAVEASDOCUMENTRESPONSE
DESCRIPTOR.message_types_by_name['ExportDesignRequest'] = _EXPORTDESIGNREQUEST
DESCRIPTOR.message_types_by_name['ExportDesignResponse'] = _EXPORTDESIGNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewDesignRequest = _reflection.GeneratedProtocolMessageType('NewDesignRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWDESIGNREQUEST,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.NewDesignRequest)
  ))
_sym_db.RegisterMessage(NewDesignRequest)

Design = _reflection.GeneratedProtocolMessageType('Design', (_message.Message,), dict(
  DESCRIPTOR = _DESIGN,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Design)
  ))
_sym_db.RegisterMessage(Design)

SaveAsDocumentRequest = _reflection.GeneratedProtocolMessageType('SaveAsDocumentRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAVEASDOCUMENTREQUEST,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.SaveAsDocumentRequest)
  ))
_sym_db.RegisterMessage(SaveAsDocumentRequest)

SaveAsDocumentResponse = _reflection.GeneratedProtocolMessageType('SaveAsDocumentResponse', (_message.Message,), dict(
  DESCRIPTOR = _SAVEASDOCUMENTRESPONSE,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.SaveAsDocumentResponse)
  ))
_sym_db.RegisterMessage(SaveAsDocumentResponse)

ExportDesignRequest = _reflection.GeneratedProtocolMessageType('ExportDesignRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTDESIGNREQUEST,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.ExportDesignRequest)
  ))
_sym_db.RegisterMessage(ExportDesignRequest)

ExportDesignResponse = _reflection.GeneratedProtocolMessageType('ExportDesignResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTDESIGNRESPONSE,
  __module__ = 'ansys.api.geometry.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.ExportDesignResponse)
  ))
_sym_db.RegisterMessage(ExportDesignResponse)


DESCRIPTOR._options = None

_DESIGNS = _descriptor.ServiceDescriptor(
  name='Designs',
  full_name='ansys.api.geometry.v0.Designs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=368,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='New',
    full_name='ansys.api.geometry.v0.Designs.New',
    index=0,
    containing_service=None,
    input_type=_NEWDESIGNREQUEST,
    output_type=_DESIGN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveAs',
    full_name='ansys.api.geometry.v0.Designs.SaveAs',
    index=1,
    containing_service=None,
    input_type=_SAVEASDOCUMENTREQUEST,
    output_type=_SAVEASDOCUMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExportDesign',
    full_name='ansys.api.geometry.v0.Designs.ExportDesign',
    index=2,
    containing_service=None,
    input_type=_EXPORTDESIGNREQUEST,
    output_type=_EXPORTDESIGNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DESIGNS)

DESCRIPTOR.services_by_name['Designs'] = _DESIGNS

# @@protoc_insertion_point(module_scope)
