from algorithms.algorithm import IAlgorithm
from algorithms.iaggregator import IAggregator
from algorithms.iclassifier import IClassifier
from algorithms.iclustering import IClustering
from algorithms.idescriptor import IDescriptor
from algorithms.idetector import IDetector
from algorithms.idistance import IDistance
from algorithms.ipoints_detector import IPointsDetector
from algorithms.ipreprocessor import IPreprocessor
from algorithms.iquality_estimator import IQualityEstimator
from algorithms.itracker import ITracker
