class Status():
    NOT_STARTED = 'NOT_STARTED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    SUCCESS = 'SUCCESS'


class TaskTypes():
    WATCH_COURSE = 'WATCH_COURSE'
    SIGN_UP = 'SIGN_UP'
    RESTART = 'RESTART'
    CHECK_USERNAME = 'CHECK_USERNAME'
    CORRUPTION_CHECK = 'CORRUPTION_CHECK'
