
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-06T02:44:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2173461784fae6e4c6b81067e366ef5d82d0dfaa",
 "version": "0.5.dev2245"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
