
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T10:47:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a91db6b96abddde192457c8b636ed13e2a7dbeda",
 "version": "1.17.1.post0.dev354"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
