
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T12:12:28-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c5f1854e30b7aa8f7ed79e28e1f48d67afa1af3",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
