VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('05')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 0
MINOR_VERSION = 21
PATCH_VERSION = 202211051359
version_date = '2022/11/05 13:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
