
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-08T15:11:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "08f7a662a36b6844e53b146271fc93b5a5c74b8a",
 "version": "0.2.41.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
