# coding: utf-8

"""
    DLCM-Solution

    DLCM application wrapping all modules, All-In-One  # noqa: E501

    The version of the OpenAPI document: 2.1.1
    Contact: eresearch-opensource@unige.ch
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from dlcmapi_client.configuration import Configuration


class MetadataType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'links': 'object',
        'creation': 'ChangeInfo',
        'description': 'str',
        'full_name': 'str',
        'last_update': 'ChangeInfo',
        'metadata_format': 'str',
        'metadata_schema': 'str',
        'name': 'str',
        'res_id': 'str',
        'url': 'str',
        'version': 'str'
    }

    attribute_map = {
        'links': '_links',
        'creation': 'creation',
        'description': 'description',
        'full_name': 'fullName',
        'last_update': 'lastUpdate',
        'metadata_format': 'metadataFormat',
        'metadata_schema': 'metadataSchema',
        'name': 'name',
        'res_id': 'resId',
        'url': 'url',
        'version': 'version'
    }

    def __init__(self, links=None, creation=None, description=None, full_name=None, last_update=None, metadata_format=None, metadata_schema=None, name=None, res_id=None, url=None, version=None, local_vars_configuration=None):  # noqa: E501
        """MetadataType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._links = None
        self._creation = None
        self._description = None
        self._full_name = None
        self._last_update = None
        self._metadata_format = None
        self._metadata_schema = None
        self._name = None
        self._res_id = None
        self._url = None
        self._version = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if creation is not None:
            self.creation = creation
        if description is not None:
            self.description = description
        if full_name is not None:
            self.full_name = full_name
        if last_update is not None:
            self.last_update = last_update
        if metadata_format is not None:
            self.metadata_format = metadata_format
        if metadata_schema is not None:
            self.metadata_schema = metadata_schema
        if name is not None:
            self.name = name
        if res_id is not None:
            self.res_id = res_id
        if url is not None:
            self.url = url
        if version is not None:
            self.version = version

    @property
    def links(self):
        """Gets the links of this MetadataType.  # noqa: E501

        The _links_ list of the _metadata-types_ resource  # noqa: E501

        :return: The links of this MetadataType.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this MetadataType.

        The _links_ list of the _metadata-types_ resource  # noqa: E501

        :param links: The links of this MetadataType.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def creation(self):
        """Gets the creation of this MetadataType.  # noqa: E501


        :return: The creation of this MetadataType.  # noqa: E501
        :rtype: ChangeInfo
        """
        return self._creation

    @creation.setter
    def creation(self, creation):
        """Sets the creation of this MetadataType.


        :param creation: The creation of this MetadataType.  # noqa: E501
        :type: ChangeInfo
        """

        self._creation = creation

    @property
    def description(self):
        """Gets the description of this MetadataType.  # noqa: E501

        The description of the metadata type  # noqa: E501

        :return: The description of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MetadataType.

        The description of the metadata type  # noqa: E501

        :param description: The description of this MetadataType.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def full_name(self):
        """Gets the full_name of this MetadataType.  # noqa: E501

        The name and the version of the metadata type  # noqa: E501

        :return: The full_name of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this MetadataType.

        The name and the version of the metadata type  # noqa: E501

        :param full_name: The full_name of this MetadataType.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def last_update(self):
        """Gets the last_update of this MetadataType.  # noqa: E501


        :return: The last_update of this MetadataType.  # noqa: E501
        :rtype: ChangeInfo
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this MetadataType.


        :param last_update: The last_update of this MetadataType.  # noqa: E501
        :type: ChangeInfo
        """

        self._last_update = last_update

    @property
    def metadata_format(self):
        """Gets the metadata_format of this MetadataType.  # noqa: E501

        The format of the metadata type  # noqa: E501

        :return: The metadata_format of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._metadata_format

    @metadata_format.setter
    def metadata_format(self, metadata_format):
        """Sets the metadata_format of this MetadataType.

        The format of the metadata type  # noqa: E501

        :param metadata_format: The metadata_format of this MetadataType.  # noqa: E501
        :type: str
        """
        allowed_values = ["CUSTOM", "JSON", "SCHEMA_LESS", "XML"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and metadata_format not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `metadata_format` ({0}), must be one of {1}"  # noqa: E501
                .format(metadata_format, allowed_values)
            )

        self._metadata_format = metadata_format

    @property
    def metadata_schema(self):
        """Gets the metadata_schema of this MetadataType.  # noqa: E501

        The schema of the metadata type  # noqa: E501

        :return: The metadata_schema of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._metadata_schema

    @metadata_schema.setter
    def metadata_schema(self, metadata_schema):
        """Sets the metadata_schema of this MetadataType.

        The schema of the metadata type  # noqa: E501

        :param metadata_schema: The metadata_schema of this MetadataType.  # noqa: E501
        :type: str
        """

        self._metadata_schema = metadata_schema

    @property
    def name(self):
        """Gets the name of this MetadataType.  # noqa: E501

        The name of the metadata type  # noqa: E501

        :return: The name of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MetadataType.

        The name of the metadata type  # noqa: E501

        :param name: The name of this MetadataType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def res_id(self):
        """Gets the res_id of this MetadataType.  # noqa: E501

        The _metadata-types_ resource identifier [https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID]]  # noqa: E501

        :return: The res_id of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._res_id

    @res_id.setter
    def res_id(self, res_id):
        """Sets the res_id of this MetadataType.

        The _metadata-types_ resource identifier [https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID]]  # noqa: E501

        :param res_id: The res_id of this MetadataType.  # noqa: E501
        :type: str
        """

        self._res_id = res_id

    @property
    def url(self):
        """Gets the url of this MetadataType.  # noqa: E501

        The URL of the metadata type  # noqa: E501

        :return: The url of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this MetadataType.

        The URL of the metadata type  # noqa: E501

        :param url: The url of this MetadataType.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def version(self):
        """Gets the version of this MetadataType.  # noqa: E501

        The version of the metadata type  # noqa: E501

        :return: The version of this MetadataType.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this MetadataType.

        The version of the metadata type  # noqa: E501

        :param version: The version of this MetadataType.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MetadataType):
            return True

        return self.to_dict() != other.to_dict()
