VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('07')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 0
MINOR_VERSION = 22
PATCH_VERSION = 202211070936
version_date = '2022/11/07 09:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
