VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('07')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('56')
MAJOR_VERSION = 0
MINOR_VERSION = 22
PATCH_VERSION = 202211070656
version_date = '2022/11/07 06:56'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
