# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from collibra_core.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ACTIVITIES = "Activities"
    APPLICATION = "Application"
    ASSET_TYPES = "Asset Types"
    ASSETS = "Assets"
    ASSIGNMENTS = "Assignments"
    ATTACHMENTS = "Attachments"
    ATTRIBUTE_TYPES = "Attribute Types"
    ATTRIBUTES = "Attributes"
    AUTHENTICATION_SESSIONS = "Authentication (Sessions)"
    COMMENTS = "Comments"
    COMMUNITIES = "Communities"
    COMPLEX_RELATION_TYPES = "Complex Relation Types"
    COMPLEX_RELATIONS = "Complex Relations"
    DATA_QUALITY_RULES = "Data Quality Rules"
    DIAGRAM_PICTURES = "Diagram Pictures"
    DOMAIN_TYPES = "Domain Types"
    DOMAINS = "Domains"
    FILES = "Files"
    ISSUES = "Issues"
    JDBC_DRIVER = "JDBC Driver"
    JOBS = "Jobs"
    MAPPINGS = "Mappings"
    NAVIGATION_STATISTICS = "Navigation Statistics"
    OUTPUT_MODULE = "Output Module"
    RATINGS = "Ratings"
    RELATION_TYPES = "Relation Types"
    RELATIONS = "Relations"
    REPORTING = "Reporting"
    RESPONSIBILITIES = "Responsibilities"
    ROLES = "Roles"
    SAML = "SAML"
    SCOPES = "Scopes"
    STATUSES = "Statuses"
    TAGS = "Tags"
    USER_GROUPS = "User Groups"
    USERS = "Users"
    VALIDATION = "Validation"
    VIEW_PERMISSIONS = "View Permissions"
    WORKFLOW_DEFINITIONS = "Workflow Definitions"
    WORKFLOW_INSTANCES = "Workflow Instances"
    WORKFLOW_TASKS = "Workflow Tasks"
