# coding: utf-8

"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_core.paths.domain_types.post import AddDomainType
from collibra_core.paths.domain_types_bulk.post import AddDomainTypes
from collibra_core.paths.domain_types_domain_type_id.patch import ChangeDomainType
from collibra_core.paths.domain_types_bulk.patch import ChangeDomainTypes
from collibra_core.paths.domain_types.get import FindDomainTypes
from collibra_core.paths.domain_types_domain_type_id_sub_types.get import FindSubDomainTypes
from collibra_core.paths.domain_types_domain_type_id.get import GetDomainType
from collibra_core.paths.domain_types_domain_type_id.delete import RemoveDomainType
from collibra_core.paths.domain_types_bulk.delete import RemoveDomainTypes


class DomainTypesApi(
    AddDomainType,
    AddDomainTypes,
    ChangeDomainType,
    ChangeDomainTypes,
    FindDomainTypes,
    FindSubDomainTypes,
    GetDomainType,
    RemoveDomainType,
    RemoveDomainTypes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
