#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['shapelyAcad']

package_data = \
{'': ['*']}

install_requires = \
['pyautocad', 'shapely', 'numpy']

extras_require = \
{'dev': ['flit',
         'flake8',
         'flake8-black',
         'flake8-docstrings',
         'black',
         'pytest',
         'isort',
         'mypy',
         'codecov',
         'pytest-cov',
         'pytest-mock',
         'bumpversion']}

setup(name='shapelyAcad',
      version='0.0.1.dev4',
      description='Draw shapley objects in AutoCAD',
      author=None,
      author_email='Hazzed <hazzed@shapelyAcad.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.10',
     )
