
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T21:23:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f31d33519fef54c4f52730f4b6917199dfa36b1",
 "version": "2022.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
