# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['octopy_admin',
 'octopy_admin.graph',
 'octopy_admin.rest',
 'octopy_admin.rest.apis',
 'octopy_admin.rest.apis.actions',
 'octopy_admin.rest.apis.activity',
 'octopy_admin.rest.apis.apps',
 'octopy_admin.rest.apis.billing',
 'octopy_admin.rest.apis.checks',
 'octopy_admin.rest.apis.code_scanning',
 'octopy_admin.rest.apis.codes_of_conduct',
 'octopy_admin.rest.apis.codespaces',
 'octopy_admin.rest.apis.dependabot',
 'octopy_admin.rest.apis.dependency_graph',
 'octopy_admin.rest.apis.emojis',
 'octopy_admin.rest.apis.enterprise_admin',
 'octopy_admin.rest.apis.gists',
 'octopy_admin.rest.apis.git',
 'octopy_admin.rest.apis.gitignore',
 'octopy_admin.rest.apis.interactions',
 'octopy_admin.rest.apis.issues',
 'octopy_admin.rest.apis.licenses',
 'octopy_admin.rest.apis.markdown',
 'octopy_admin.rest.apis.merge_queue',
 'octopy_admin.rest.apis.meta',
 'octopy_admin.rest.apis.migrations',
 'octopy_admin.rest.apis.orgs',
 'octopy_admin.rest.apis.packages',
 'octopy_admin.rest.apis.projects',
 'octopy_admin.rest.apis.pulls',
 'octopy_admin.rest.apis.rate_limit',
 'octopy_admin.rest.apis.reactions',
 'octopy_admin.rest.apis.repos',
 'octopy_admin.rest.apis.search',
 'octopy_admin.rest.apis.secret_scanning',
 'octopy_admin.rest.apis.server_statistics',
 'octopy_admin.rest.apis.teams',
 'octopy_admin.rest.apis.users',
 'octopy_admin.rest_enterprise_cloud',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.actions',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.activity',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.apps',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.billing',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.checks',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.code_scanning',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.codes_of_conduct',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.codespaces',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.dependabot',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.dependency_graph',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.emojis',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.enterprise_admin',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.gists',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.git',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.gitignore',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.interactions',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.issues',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.licenses',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.markdown',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.merge_queue',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.meta',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.migrations',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.oidc',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.orgs',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.packages',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.projects',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.pulls',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.rate_limit',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.reactions',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.repos',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.scim',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.search',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.secret_scanning',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.server_statistics',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.teams',
 'octopy_admin.rest_enterprise_cloud.apis_enterprise_cloud.users',
 'octopy_admin.rest_enterprise_server',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.actions',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.activity',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.apps',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.billing',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.checks',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.code_scanning',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.codes_of_conduct',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.codespaces',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.dependabot',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.dependency_graph',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.emojis',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.enterprise_admin',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.gists',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.git',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.gitignore',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.interactions',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.issues',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.licenses',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.markdown',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.merge_queue',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.meta',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.migrations',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.oauth_authorizations',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.orgs',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.packages',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.projects',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.pulls',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.rate_limit',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.reactions',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.repos',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.search',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.secret_scanning',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.server_statistics',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.teams',
 'octopy_admin.rest_enterprise_server.apis_enterprise_server.users']

package_data = \
{'': ['*'], 'octopy_admin.graph': ['gql_files/*']}

install_requires = \
['aiohttp>=3.8.1,<4.0.0', 'gql>=3.4.0,<4.0.0', 'requests>=2.28.1,<3.0.0']

setup_kwargs = {
    'name': 'octopy-admin',
    'version': '0.2.9',
    'description': 'OctoPy Admin is a python library for interacting with the GitHub GraphQL and REST APIs.',
    'long_description': 'None',
    'author': 'Brett Kuhlman',
    'author_email': 'kuhlman-labs@github.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
