# coding: utf-8

"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_core.paths.output_module_export_csv.post import ExportCsv
from collibra_core.paths.output_module_export_csv_job.post import ExportCsvinJob
from collibra_core.paths.output_module_export_csv_file.post import ExportCsvtoFile
from collibra_core.paths.output_module_export_excel_job.post import ExportExcelInJob
from collibra_core.paths.output_module_export_excel_file.post import ExportExcelToFile
from collibra_core.paths.output_module_export_json.post import ExportJson
from collibra_core.paths.output_module_export_json_job.post import ExportJsoninJob
from collibra_core.paths.output_module_export_json_file.post import ExportJsontoFile
from collibra_core.paths.output_module_export_xml.post import ExportXml
from collibra_core.paths.output_module_export_xml_job.post import ExportXmlinJob
from collibra_core.paths.output_module_export_xml_file.post import ExportXmltoFile
from collibra_core.paths.output_module_table_view_configs_view_id_view_id.get import GetTableViewConfigByViewId


class OutputModuleApi(
    ExportCsv,
    ExportCsvinJob,
    ExportCsvtoFile,
    ExportExcelInJob,
    ExportExcelToFile,
    ExportJson,
    ExportJsoninJob,
    ExportJsontoFile,
    ExportXml,
    ExportXmlinJob,
    ExportXmltoFile,
    GetTableViewConfigByViewId,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
