{
 "title": "vSphere - Overview",
 "description": "Small overview dashboard for VMware vSphere environments",
 "tags": [
  "vsphere",
  "telegraf",
  "demo"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vc",
    "label": "vCenter",
    "query": "show tag values with key = \"vcenter\""
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"clustername\" where \"vcenter\" =~/$vc/"
   },
   {
    "name": "time",
    "label": "Time",
    "query": "20s,1m,5m,15m,30m,1h,12h,24h,1w,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Clusters",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"vmname\")) FROM (SELECT \"usage_average\", \"clustername\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter AND \"clustername\" =~ /$cluster/ AND \"vcenter\" =~ /$vc/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Hosts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"esxhostname\")) FROM (SELECT \"usage_average\", \"esxhostname\" FROM  \"vsphere_host_cpu\" WHERE $timeFilter AND \"clustername\" =~ /$cluster/ AND \"vcenter\" =~ /$vc/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"vmname\")) FROM (SELECT \"usage_average\", \"vmname\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter AND \"clustername\" =~ /$cluster/ AND \"vcenter\" =~ /$vc/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Datastores",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT count(distinct(\"dsname\")) FROM (SELECT \"read_average\", \"dsname\" FROM  \"vsphere_host_datastore\" WHERE $timeFilter AND \"clustername\" =~ /$cluster/ AND \"vcenter\" =~ /$vc/)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    },
    {
     "alias": "NET",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    },
    {
     "alias": "Storage Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_datastore",
     "select": [
      [
       { "params": [ "maxTotalLatency_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "vcenter", "operator": "=~", "value": "/^$vc$/" }
     ]
    }
   ]
  }
 ]
}