{
 "title": "vSphere - VM details",
 "description": "Dashboard for VM metrics in a VMware vSphere environments",
 "tags": [
  "telegraf",
  "vsphere"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vc",
    "label": "vCenter",
    "query": "show tag values with key = \"vcenter\""
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"clustername\" where \"vcenter\" =~/$vc/"
   },
   {
    "name": "host",
    "label": "ESXi",
    "query": "show tag values with key = \"esxhostname\" where \"clustername\" =~/$cluster/ and \"vcenter\" =~/$vc/"
   },
   {
    "name": "vm",
    "label": "VM",
    "query": "show tag values with key = \"vmname\" where \"esxhostname\" =~/$host/ and \"vcenter\" =~/$vc/"
   },
   {
    "name": "time",
    "label": "Time",
    "query": "20s,1m,5m,15m,30m,1h,12h,24h,1w,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "VM Details - $vm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "vsphere_vm_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "CPUs",
     "measurement": "vsphere_vm_cpu",
     "query": "SELECT count(distinct(\"cpu\")) FROM (SELECT \"run_summation\", \"cpu\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter AND \"vmname\" =~ /$vm/ AND \"cpu\" != 'instance-total')",
     "select": [
      [
       { "params": [ "run_summation" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "NET",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Storage Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_datastore",
     "select": [
      [
       { "params": [ "maxTotalLatency_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "ready_summation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "latency_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Consumed vs Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    },
    {
     "alias": "Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "consumed_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consumed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "NET Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "NET Transmit / Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "receive" ], "type": "alias" }
      ],
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "transmit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col-$tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$vm$/" }
     ]
    }
   ]
  }
 ]
}