
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-09T11:21:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "29590abf18cb23990eebba3c5b9a0d1bc2be45b7",
 "version": "v1.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
