# coding: utf-8

"""
    Collibra Import API

    <p>The Import API is an efficient way to load large volumes of data into the Collibra Data Governance Center. The API can automatically differentiate between creating and updating data.</p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from collibra_importer.paths.import_synchronize_synchronization_id_evict.delete import EvictSynchronizationCache
from collibra_importer.paths.import_synchronize_exists_synchronization_id.get import Exists
from collibra_importer.paths.import_synchronize.get import FindSynchronizationInfos
from collibra_importer.paths.import_csv_job.post import ImportCsvInJob
from collibra_importer.paths.import_excel_job.post import ImportExcelInJob
from collibra_importer.paths.import_json_job.post import ImportJsonInJob
from collibra_importer.paths.import_synchronize_synchronization_id.delete import RemoveSynchronization
from collibra_importer.paths.import_synchronize_synchronization_id_batch_csv_job.post import SynchronizeBatchCsvInJob
from collibra_importer.paths.import_synchronize_synchronization_id_batch_excel_job.post import SynchronizeBatchExcelInJob
from collibra_importer.paths.import_synchronize_synchronization_id_batch_json_job.post import SynchronizeBatchJsonInJob
from collibra_importer.paths.import_synchronize_synchronization_id_csv_job.post import SynchronizeCsvInJob
from collibra_importer.paths.import_synchronize_synchronization_id_excel_job.post import SynchronizeExcelInJob
from collibra_importer.paths.import_synchronize_synchronization_id_finalize_job.post import SynchronizeFinalizeInJob
from collibra_importer.paths.import_synchronize_synchronization_id_json_job.post import SynchronizeJsonInJob


class ModelImportApi(
    EvictSynchronizationCache,
    Exists,
    FindSynchronizationInfos,
    ImportCsvInJob,
    ImportExcelInJob,
    ImportJsonInJob,
    RemoveSynchronization,
    SynchronizeBatchCsvInJob,
    SynchronizeBatchExcelInJob,
    SynchronizeBatchJsonInJob,
    SynchronizeCsvInJob,
    SynchronizeExcelInJob,
    SynchronizeFinalizeInJob,
    SynchronizeJsonInJob,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
