
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T12:07:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c2d612b318dd4346baa3afb6f7cb2e064510e17",
 "version": "2.0.0b12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
