
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-04T20:20:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "887f0848f0d5f29f884b69aec30214b26b079e40",
 "version": "v0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
