VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('09')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('40')
MAJOR_VERSION = 0
MINOR_VERSION = 23
PATCH_VERSION = 202211091640
version_date = '2022/11/09 16:40'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
