
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-27T10:21:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "57b01aa7fd65c0c2d9374aa2b2d9a7ba360605f8",
 "version": "2.1.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
