
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-07T17:35:26-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dfb218fac7d659cc26cb181789998375b00f5c4",
 "version": "7.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
